using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.Soyuz.MagicBook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Client.DeadSpace.Soyuz.MagicBook;

[GenerateTypedNameReferences]
public sealed partial class MagicBookWindow : FancyWindow
{
    private readonly Button[] _slotButtons;

    private MagicBookBoundUserInterfaceState? _state;
    private int _selectedSlot;
    private int _lastActivePage = -2;
    private string _searchText = string.Empty;
    private MagicRuneCategory? _filterCategory;

    public event Action? OnInsertPage;
    public event Action<int>? OnPageSelected;
    public event Action<int, int>? OnRuneSlotSet;
    public event Action<int>? OnRuneSlotCleared;
    public event Action<string>? OnSaveSpell;

    public MagicBookWindow()
    {
        RobustXamlLoader.Load(this);

        _slotButtons = new[] { SlotOne, SlotTwo, SlotThree, SlotFour, SlotFive };
        for (var i = 0; i < _slotButtons.Length; i++)
        {
            var slot = i;
            _slotButtons[i].OnButtonDown += args =>
            {
                if (args.Event.Function == EngineKeyFunctions.UIRightClick)
                    OnRuneSlotCleared?.Invoke(slot);
                else
                    SelectSlot(slot);
            };
        }

        InsertPageButton.OnPressed += _ => OnInsertPage?.Invoke();
        SaveButton.OnPressed += _ => OnSaveSpell?.Invoke(SpellName.Text);
        SearchInput.OnTextChanged += args =>
        {
            _searchText = args.Text.Trim().ToLowerInvariant();
            RebuildRuneList();
        };

        CategoryFilter.AddItem("Все", 0);
        CategoryFilter.AddItem("Формы", 1);
        CategoryFilter.AddItem("Модификаторы", 2);
        CategoryFilter.AddItem("Эффекты", 3);
        CategoryFilter.SelectId(0);
        CategoryFilter.OnItemSelected += args =>
        {
            CategoryFilter.SelectId(args.Id);
            _filterCategory = args.Id switch
            {
                1 => MagicRuneCategory.Form,
                2 => MagicRuneCategory.Modifier,
                3 => MagicRuneCategory.Effect,
                _ => null
            };
            RebuildRuneList();
        };

        SelectSlot(0);
    }

    public void UpdateState(MagicBookBoundUserInterfaceState state)
    {
        _state = state;

        StateLabel.Text = state.PagesUnlocked
            ? "Ритуал завершен. Страницы принимаются."
            : "Страницы заблокированы.";

        HeaderCounterLabel.Text = $"{state.Pages.Length} / {state.MaxPages}";
        PageStateHint.Text = state.PagesUnlocked ? "UNLOCKED" : "LOCKED";
        RuneCountLabel.Text = $"{state.KnownRunes.Length}";

        InsertPageButton.Disabled = !state.PagesUnlocked || state.Pages.Length >= state.MaxPages;
        InsertPageButton.ToolTip = !state.PagesUnlocked
            ? "Требуется завершить ритуал"
            : "Вставить вырванную страницу из активной руки";

        if (_lastActivePage != state.ActivePage)
        {
            SpellName.Text = GetActivePage()?.Spell.Name ?? string.Empty;
            _lastActivePage = state.ActivePage;
        }

        RebuildPageList();
        UpdateSlots();
        UpdatePreview();
        RebuildRuneList();
    }

    private void RebuildPageList()
    {
        PageList.RemoveAllChildren();

        if (_state == null)
            return;

        for (var i = 0; i < _state.Pages.Length; i++)
        {
            var page = _state.Pages[i];
            var index = i;
            var spellName = string.IsNullOrWhiteSpace(page.Spell.Name)
                ? $"Страница {i + 1}"
                : page.Spell.Name;

            var button = new Button
            {
                Text = $"{i + 1:00}  {PageStateText(page.PageState)}\n{spellName}",
                HorizontalExpand = true,
                MinHeight = 48,
                Pressed = i == _state.ActivePage,
                ToggleMode = true,
                ToolTip = page.Spell.IsValid && !string.IsNullOrWhiteSpace(page.Spell.Name)
                    ? page.Spell.Name
                    : PageStateText(page.PageState),
            };
            button.OnPressed += _ => OnPageSelected?.Invoke(index);
            PageList.AddChild(button);
        }
    }

    private void UpdateSlots()
    {
        var page = GetActivePage();
        var editable = page != null && page.PageState != MagicBookPageState.Saved && page.PageState != MagicBookPageState.Broken;

        PageTitle.Text = page == null
            ? "Нет вставленной страницы"
            : $"Страница {_state!.ActivePage + 1}: {PageStateText(page.PageState)}";

        SelectedSlotLabel.Text = $"Слот {_selectedSlot + 1}";
        RuneSlotHint.Text = _selectedSlot == 0
            ? "Выбран первый слот: доступны только руны FORM."
            : "Выбран слот сборки: доступны MODIFIER и EFFECT.";

        for (var i = 0; i < _slotButtons.Length; i++)
        {
            var button = _slotButtons[i];
            button.Disabled = !editable;
            button.Pressed = i == _selectedSlot;
            button.ToggleMode = true;
            button.ToolTip = i == 0
                ? "Первый слот принимает только FORM. ПКМ очищает слот."
                : "Слоты 2-5 принимают MODIFIER или EFFECT. ПКМ очищает слот.";

            var runeIndex = page?.Spell.Runes.Length > i ? page.Spell.Runes[i] : -1;
            var rune = runeIndex >= 0 ? GetRune(runeIndex) : null;
            button.Text = rune == null
                ? SlotPlaceholder(i)
                : $"{i + 1}. {rune.Name}\n{CategoryText(rune.Category)}";
        }

        if (!editable)
            SaveButton.Disabled = true;
    }

    private void UpdatePreview()
    {
        if (_state == null)
            return;

        var page = GetActivePage();
        var preview = _state.Preview;
        var editable = page != null && page.PageState != MagicBookPageState.Saved && page.PageState != MagicBookPageState.Broken;

        if (page != null && page.PageState == MagicBookPageState.Saved && string.IsNullOrWhiteSpace(SpellName.Text))
            SpellName.Text = page.Spell.Name;

        SpellName.Editable = editable;

        var effects = preview.Effects.Length == 0
            ? "нет"
            : string.Join(", ", preview.Effects.Select(index => GetRune(index)?.Name ?? $"#{index + 1}"));

        ManaCostValue.Text = preview.ManaCost.ToString();
        StabilityValue.Text = $"{preview.Stability:0}%";
        RiskValue.Text = $"{preview.Risk:0}%";
        EffectsValue.Text = effects;
        PreviewStatus.Text = preview.IsValid ? "VALID" : "INVALID";

        ValidationPanel.Visible = preview.ValidationErrors.Length > 0;
        ErrorsLabel.Text = preview.ValidationErrors.Length == 0
            ? string.Empty
            : string.Join("\n", preview.ValidationErrors);

        SaveButton.Disabled = !editable || !preview.IsValid;
        SaveButton.ToolTip = preview.IsValid
            ? "Сохранить и добавить в меню способностей"
            : "Заклинание не прошло валидацию";
    }

    private void RebuildRuneList()
    {
        RuneList.RemoveAllChildren();

        if (_state == null)
            return;

        var page = GetActivePage();
        var hasEditablePage = page != null &&
                              page.PageState != MagicBookPageState.Saved &&
                              page.PageState != MagicBookPageState.Broken;

        var runes = _state.KnownRunes
            .Where(rune => _filterCategory == null || rune.Category == _filterCategory)
            .Where(rune => string.IsNullOrEmpty(_searchText) || rune.Name.ToLowerInvariant().Contains(_searchText))
            .OrderBy(rune => rune.Category)
            .ThenBy(rune => rune.Index)
            .ToArray();

        RuneCountLabel.Text = $"{runes.Length}/{_state.KnownRunes.Length}";

        foreach (var rune in runes)
        {
            var allowedBySlot = _selectedSlot == 0
                ? rune.Category == MagicRuneCategory.Form
                : rune.Category != MagicRuneCategory.Form;

            var button = new Button
            {
                Text = $"{rune.Name}\n{CategoryText(rune.Category)}   mana {rune.ManaCost}   {StackText(rune)}",
                HorizontalExpand = true,
                MinHeight = 52,
                Disabled = !hasEditablePage || !allowedBySlot,
                ToolTip = BuildRuneTooltip(rune, allowedBySlot),
            };

            button.OnPressed += _ =>
            {
                if (hasEditablePage && allowedBySlot)
                    OnRuneSlotSet?.Invoke(_selectedSlot, rune.Index);
            };

            RuneList.AddChild(button);
        }
    }

    private MagicBookPageUiState? GetActivePage()
    {
        if (_state == null || _state.ActivePage < 0 || _state.ActivePage >= _state.Pages.Length)
            return null;

        return _state.Pages[_state.ActivePage];
    }

    private MagicBookRuneUiEntry? GetRune(int index)
    {
        return _state?.KnownRunes.FirstOrDefault(rune => rune.Index == index);
    }

    private void SelectSlot(int slot)
    {
        _selectedSlot = Math.Clamp(slot, 0, _slotButtons.Length - 1);
        UpdateSlots();
        RebuildRuneList();
    }

    private static string SlotPlaceholder(int slot)
    {
        return slot == 0
            ? "1. FORM"
            : $"{slot + 1}. MODIFIER / EFFECT";
    }

    private static string CategoryText(MagicRuneCategory category)
    {
        return category switch
        {
            MagicRuneCategory.Form => "FORM",
            MagicRuneCategory.Modifier => "MODIFIER",
            MagicRuneCategory.Effect => "EFFECT",
            _ => "?"
        };
    }

    private static string PageStateText(MagicBookPageState state)
    {
        return state switch
        {
            MagicBookPageState.Empty => "EMPTY",
            MagicBookPageState.Editing => "EDITING",
            MagicBookPageState.Saved => "SAVED",
            MagicBookPageState.Broken => "BROKEN",
            _ => "?"
        };
    }

    private static string StackText(MagicBookRuneUiEntry rune)
    {
        return rune.Stackable ? $"stack {rune.MaxStacks}" : "single";
    }

    private static string BuildRuneTooltip(MagicBookRuneUiEntry rune, bool allowedBySlot)
    {
        var tags = rune.Tags.Length == 0 ? "без тегов" : string.Join(", ", rune.Tags);
        var stack = rune.Stackable ? $"стакается до {rune.MaxStacks}" : "не стакается";
        var slot = allowedBySlot ? string.Empty : "\nНе подходит для выбранного слота.";
        return $"{rune.PrototypeId}\n{tags}\n{stack}\nhandler: {rune.EffectHandler}{slot}";
    }
}
