using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.Shuttles.Events;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class EmergencyConsoleWindow : FancyWindow,
    IComputerWindow<EmergencyConsoleBoundUserInterfaceState>
{
    private readonly IGameTiming _timing;
    private TimeSpan? _earlyLaunchTime;
    // DS14-start
    private bool _earlyLaunchAllowed;
    private TimeSpan? _hijackCompletionTime;
    private bool _hijackCompleted;
    private bool _canStartHijack;
    private bool _canCancelHijack;
    private string _hijackerName = string.Empty;
    // DS14-end

    public EmergencyConsoleWindow()
    {
        _timing = IoCManager.Resolve<IGameTiming>();
        RobustXamlLoader.Load(this);
    }

    public void SetupComputerWindow(ComputerBoundUserInterfaceBase cb)
    {
        RepealAllButton.OnPressed += args =>
        {
            OnRepealAllPressed(cb, args);
        };
        AuthorizeButton.OnPressed += args =>
        {
            OnAuthorizePressed(cb, args);
        };
        RepealButton.OnPressed += args =>
        {
            OnRepealPressed(cb, args);
        };
        // DS14-start
        HijackStartButton.OnPressed += args =>
        {
            OnHijackStartPressed(cb, args);
        };
        HijackCancelButton.OnPressed += args =>
        {
            OnHijackCancelPressed(cb, args);
        };
        UpdateHijackControls();
        // DS14-end
    }

    private void OnRepealAllPressed(ComputerBoundUserInterfaceBase cb, BaseButton.ButtonEventArgs obj)
    {
        cb.SendMessage(new EmergencyShuttleRepealAllMessage());
    }

    private void OnRepealPressed(ComputerBoundUserInterfaceBase cb, BaseButton.ButtonEventArgs obj)
    {
        cb.SendMessage(new EmergencyShuttleRepealMessage());
    }

    private void OnAuthorizePressed(ComputerBoundUserInterfaceBase cb, BaseButton.ButtonEventArgs obj)
    {
        cb.SendMessage(new EmergencyShuttleAuthorizeMessage());
    }

    // DS14-start
    private void OnHijackStartPressed(ComputerBoundUserInterfaceBase cb, BaseButton.ButtonEventArgs obj)
    {
        cb.SendMessage(new EmergencyShuttleHijackStartMessage());
    }

    private void OnHijackCancelPressed(ComputerBoundUserInterfaceBase cb, BaseButton.ButtonEventArgs obj)
    {
        cb.SendMessage(new EmergencyShuttleHijackCancelMessage());
    }
    // DS14-end

    public void UpdateState(EmergencyConsoleBoundUserInterfaceState scc)
    {
        // TODO: Loc and cvar for this.
        _earlyLaunchTime = scc.EarlyLaunchTime;
        // DS14-start
        _earlyLaunchAllowed = scc.EarlyLaunchAllowed;
        _hijackCompletionTime = scc.HijackCompletionTime;
        _hijackCompleted = scc.HijackCompleted;
        _hijackerName = scc.HijackerName;

        LaunchContainer.Visible = _earlyLaunchAllowed;
        AuthorizeContainer.Visible = _earlyLaunchAllowed;
        AuthorizationsTextContainer.Visible = _earlyLaunchAllowed;
        AuthorizationsPanel.Visible = _earlyLaunchAllowed;
        AuthorizationsContainer.Visible = _earlyLaunchAllowed;
        // DS14-end

        AuthorizationsContainer.RemoveAllChildren();
        var remainingAuths = scc.AuthorizationsRequired - scc.Authorizations.Count;
        AuthorizationCount.Text = Loc.GetString("emergency-shuttle-ui-remaining", ("remaining", remainingAuths));

        foreach (var auth in scc.Authorizations)
        {
            AuthorizationsContainer.AddChild(new Label
            {
                Text = auth,
                FontColorOverride = Color.Lime,
            });
        }

        UpdateHijackControls(); // DS14
    }

    // DS14-start
    public void ReceiveMessage(BoundUserInterfaceMessage message)
    {
        if (message is not EmergencyShuttleHijackAvailabilityMessage availability)
            return;

        _canStartHijack = availability.CanStart;
        _canCancelHijack = availability.CanCancel;
        UpdateHijackControls();
    }

    private void UpdateHijackControls()
    {
        if (_hijackCompleted)
        {
            HijackContainer.Visible = true;
            HijackStartButton.Visible = false;
            HijackCancelButton.Visible = false;
            HijackStatus.Text = Loc.GetString("emergency-shuttle-ui-hijack-complete");
            return;
        }

        if (_hijackCompletionTime != null)
        {
            HijackContainer.Visible = true;
            HijackStartButton.Visible = false;
            HijackCancelButton.Visible = _canCancelHijack;
            UpdateHijackCountdown();
            return;
        }

        HijackContainer.Visible = _canStartHijack;
        HijackStartButton.Visible = _canStartHijack;
        HijackCancelButton.Visible = false;
        HijackStatus.Text = Loc.GetString("emergency-shuttle-ui-hijack-inactive");
    }

    private void UpdateHijackCountdown()
    {
        if (_hijackCompletionTime == null)
            return;

        var remaining = _hijackCompletionTime.Value - _timing.CurTime;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        HijackStatus.Text = Loc.GetString(
            "emergency-shuttle-ui-hijack-active",
            ("time", FormatCountdown(remaining)));
    }

    private static string FormatCountdown(TimeSpan remaining)
    {
        return $"{(int) remaining.TotalMinutes:00}:{remaining.Seconds:00}";
    }

    private bool IsHijackRouteActive()
    {
        return _hijackCompletionTime != null || _hijackCompleted;
    }
    // DS14-end

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        // DS14-start
        if (IsHijackRouteActive())
        {
            var name = string.IsNullOrWhiteSpace(_hijackerName)
                ? Loc.GetString("emergency-shuttle-ui-hijack-unknown")
                : _hijackerName;

            Countdown.Text = Loc.GetString("emergency-shuttle-ui-hijack-welcome", ("name", name));
            Countdown.FontColorOverride = Color.Red;
            EngineStatus.Text = Loc.GetString("emergency-shuttle-ui-route-raider-outpost");
            EngineStatus.FontColorOverride = Color.Red;
        }
        else
        {
            Countdown.FontColorOverride = null;
            EngineStatus.Text = Loc.GetString("map-name-centcomm");
            EngineStatus.FontColorOverride = Color.Orange;

            if (_earlyLaunchTime == null)
            {
                Countdown.Text = Loc.GetString(_earlyLaunchAllowed
                    ? "emergency-shuttle-ui-status-waiting"
                    : "emergency-shuttle-ui-status-early-disabled");
            }
            else
            {
                var remaining = _earlyLaunchTime.Value - _timing.CurTime;

                if (remaining < TimeSpan.Zero)
                    remaining = TimeSpan.Zero;

                Countdown.Text = Loc.GetString("emergency-shuttle-ui-status-countdown", ("time", FormatCountdown(remaining)));
            }
        }

        if (_hijackCompletionTime != null)
            UpdateHijackCountdown();
        // DS14-end
    }
}
