using System.Numerics;
using Content.Client.DeadSpace.Stylesheets;
using Content.Shared.DeadSpace.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminMenuWindow : DefaultWindow
{
    public event Action? OnDisposed;

    public AdminMenuWindow()
    {
        MinSize = new Vector2(720, 360); // DS14
        Title = Loc.GetString("admin-menu-title");
        RobustXamlLoader.Load(this);
        ApplyMkStyle(MasterTabContainer); // DS14
        
        MasterTabContainer.SetTabTitle((int) TabIndex.Admin, Loc.GetString("admin-menu-admin-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Adminbus, Loc.GetString("admin-menu-adminbus-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Atmos, Loc.GetString("admin-menu-atmos-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Round, Loc.GetString("admin-menu-round-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Server, Loc.GetString("admin-menu-server-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.PanicBunker, Loc.GetString("admin-menu-panic-bunker-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Players, Loc.GetString("admin-menu-players-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Objects, Loc.GetString("admin-menu-objects-tab"));
        MasterTabContainer.OnTabChanged += OnTabChanged;
    }

    // DS14-start
    public void UpdateAutoMapVoteState(AutoMapVoteAdminState? state)
    {
        RoundTabControl.UpdateAutoMapVoteState(state);
        ServerTabControl.UpdateAutoMapVoteState(state);
    }
    // DS14-end

    private void OnTabChanged(int tabIndex)
    {
        var tabEnum = (TabIndex)tabIndex;
        if (tabEnum == TabIndex.Objects)
            ObjectsTabControl.RefreshObjectList();
    }

    // DS14-start
    private static void ApplyMkStyle(Control control)
    {
        if (IsDeadSpaceAdminCustomControl(control))
            return;

        switch (control)
        {
            case OptionButton option:
                AddStyleClass(option, DeadSpaceMenuSheetlet.ProfileControl);
                if (!option.OptionStyleClasses.Contains(DeadSpaceMenuSheetlet.ProfileControl))
                    option.OptionStyleClasses.Add(DeadSpaceMenuSheetlet.ProfileControl);
                break;
            case CheckBox checkBox:
                AddStyleClass(checkBox, DeadSpaceMenuSheetlet.ProfileControl);
                checkBox.Label.AddStyleClass(DeadSpaceMenuSheetlet.ProfileLabel);
                break;
            case Button button:
                AddStyleClass(button, DeadSpaceMenuSheetlet.ProfileControl);
                button.TextAlign = Label.AlignMode.Center;
                button.Label.HorizontalExpand = true;
                button.Label.HorizontalAlignment = HAlignment.Stretch;
                button.Label.Align = Label.AlignMode.Center;
                break;
            case LineEdit lineEdit:
                AddStyleClass(lineEdit, DeadSpaceMenuSheetlet.Input);
                break;
            case TextEdit textEdit:
                AddStyleClass(textEdit, DeadSpaceMenuSheetlet.TextArea);
                break;
            case Label label:
                AddStyleClass(label, DeadSpaceMenuSheetlet.ProfileLabel);
                break;
        }

        foreach (var child in control.Children)
        {
            ApplyMkStyle(child);
        }
    }

    private static bool IsDeadSpaceAdminCustomControl(Control control)
    {
        return control.GetType().Namespace == "Content.Client.DeadSpace.Administration.UI";
    }

    private static void AddStyleClass(Control control, string styleClass)
    {
        if (!control.StyleClasses.Contains(styleClass))
            control.AddStyleClass(styleClass);
    }
    // DS14-end

    protected override void Dispose(bool disposing)
    {
        // DS14-start
        if (disposing)
        {
            MasterTabContainer.OnTabChanged -= OnTabChanged;
        }
        // DS14-end

        OnDisposed?.Invoke();
        base.Dispose(disposing);
        OnDisposed = null;
    }

    private enum TabIndex
    {
        Admin = 0,
        Adminbus,
        Atmos,
        Round,
        Server,
        PanicBunker,
        Players,
        Objects,
    }
}
