// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Administration.UI.BanPanel;

[GenerateTypedNameReferences]
public sealed partial class BanTemplatesWindow : DefaultWindow
{
    public event Action<string, bool>? OnTemplateSelected;

    private readonly List<BanTemplate> _templates = new()
    {
        new("Перманентная", "Перманентная блокировка, Правило X, рецидив(если имеется): [краткое, понятное описание ситуации]. Обжалование в Discord."),
        new("Перманентная блокировка ДК", "Перма ДК. Правило X: [краткое, понятное описание ситуации]. Просим откликнуться на нашем Discord сервере в канале с обжалованиями."),
        new("Перманентная блокировка ДК (жалоба)", "Перма ДК. На вас поступила жалоба, просим откликнуться в канале жалоб на игроков. [Ссылка на жалобу]."),
        new("Бан роли/отдела (нарушение)", "Правило X, рецидив(если имеется): [Краткое ,понятное описание ситуации]. Обжалование в Discord."),
        new("Перманентная блокировка для прохождения теста на ЛРП", "Перма для прохождения теста. [Краткое, понятное описание ситуации]. Убедительная просьба написать обжалование в Discord, дабы получить ссылку на прохождение теста на ваши знание РП."),
        new("Перманентная блокировка для прохождения теста на ЕРП", "Перма для прохождения теста на ЕРП. [Краткое, понятное описание ситуации]. Убедительная просьба написать обжалование в Discord, дабы получить ссылку на прохождение специального теста."),
        new("Бан роли/отдела (лив/АФК)", "Правило X: [лив на ответственной должности/афк на определенной должности больше 20 минут]. Обжалование в Discord."),
        new("Временная блокировка", "Правило X, рецидив(если имеется):[Краткое,понятное описание ситуации]. Обжалование в Discord."),
        new("Наблюдение", "[Краткий текст, описывающий причины установления наблюдения].", true),
        new("Перманентная блокировка (набегаторы)", "Перманентная блокировка, Правило 0: Набегатор. [краткое, понятное описание ситуации]. Бан в реестр. Обжалование в Discord."),
        new("Перманентная блокировка для коммуникации (подозрение на набег)", "Правило 0. Подозрение на набег. [Краткое описание ситуации]. Просим вас откликнуться в нашем Discord сервере в канале обжалований."),
        new("Перманентная блокировка БВО", "Правило X, [Краткое, понятное описания ситуации]. Без возможности обжалования."),
    };

    public BanTemplatesWindow()
    {
        RobustXamlLoader.Load(this);

        foreach (var template in _templates)
        {
            var button = new Button
            {
                Text = template.Name,
                Margin = new Thickness(4)
            };
            button.OnPressed += _ =>
            {
                OnTemplateSelected?.Invoke(template.Reason, template.IsWatchlist);
                Close();
            };
            TemplatesContainer.AddChild(button);
        }
    }

    private readonly record struct BanTemplate(string Name, string Reason, bool IsWatchlist = false);
}
