using System;
using System.Collections.Generic;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Input;
using Robust.Shared.Player;
using Robust.Shared.Timing;
using Robust.Shared.Maths;

namespace Content.Client.DeadSpace.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class SnakeCartridgeFragment : BoxContainer
{
    private SnakeBoardView _boardView = default!;
    private int _highScore;

    public SnakeCartridgeFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        _boardView = new SnakeBoardView();
        BoardContainer.AddChild(_boardView);

        UpBtn.OnPressed += _ => _boardView.ChangeDirection(Direction.Up);
        DownBtn.OnPressed += _ => _boardView.ChangeDirection(Direction.Down);
        LeftBtn.OnPressed += _ => _boardView.ChangeDirection(Direction.Left);
        RightBtn.OnPressed += _ => _boardView.ChangeDirection(Direction.Right);
        NewGameBtn.OnPressed += _ =>
        {
            _boardView.ResetGame();
            ScoreLabel.Text = "Счёт: 0";
        };

        _boardView.OnScoreChanged += score =>
        {
            ScoreLabel.Text = $"Счёт: {score}";
            if (score > _highScore)
            {
                _highScore = score;
                HighScoreLabel.Text = $"Рекорд: {_highScore}";
            }
        };
    }

    private enum Direction { Up, Down, Left, Right }

    private sealed class SnakeBoardView : Control
    {
        private const int GridSize = 20;
        private const float TickInterval = 0.2f;

        private readonly List<(int X, int Y)> _snake = new();
        private Direction _direction;
        private Direction _nextDirection;
        private (int X, int Y) _food;
        private int _score;
        private bool _gameOver;
        private TimeSpan _lastTick;
        private readonly IGameTiming _timing;
        private readonly SharedAudioSystem _audio;
        private readonly Random _random = new();

        public event Action<int>? OnScoreChanged;

        public SnakeBoardView()
        {
            CanKeyboardFocus = true;
            _timing = IoCManager.Resolve<IGameTiming>();
            _audio = IoCManager.Resolve<IEntityManager>().System<SharedAudioSystem>();

            OnKeyBindDown += OnKeyPressed;

            ResetGame();
        }

        private void OnKeyPressed(GUIBoundKeyEventArgs args)
        {
            if (_gameOver && (args.Function == EngineKeyFunctions.TextCursorUp
                || args.Function == EngineKeyFunctions.TextCursorDown
                || args.Function == EngineKeyFunctions.TextCursorLeft
                || args.Function == EngineKeyFunctions.TextCursorRight
                || args.Function == "Use"))
            {
                ResetGame();
                OnScoreChanged?.Invoke(0);
                return;
            }

            if (args.Function == EngineKeyFunctions.TextCursorUp || args.Function == "MoveUp")
                ChangeDirection(Direction.Up);
            else if (args.Function == EngineKeyFunctions.TextCursorDown || args.Function == "MoveDown")
                ChangeDirection(Direction.Down);
            else if (args.Function == EngineKeyFunctions.TextCursorLeft || args.Function == "MoveLeft")
                ChangeDirection(Direction.Left);
            else if (args.Function == EngineKeyFunctions.TextCursorRight || args.Function == "MoveRight")
                ChangeDirection(Direction.Right);
        }

        public void ResetGame()
        {
            _snake.Clear();
            for (var i = 0; i < 3; i++)
                _snake.Add((GridSize / 2 - i, GridSize / 2));
            _direction = Direction.Right;
            _nextDirection = Direction.Right;
            _score = 0;
            _gameOver = false;
            _lastTick = _timing.RealTime;
            SpawnFood();
            _audio.PlayGlobal(new SoundPathSpecifier("/Audio/Effects/Arcade/newgame.ogg"), Filter.Local(), false);
        }

        public void ChangeDirection(Direction dir)
        {
            if (dir == _nextDirection)
                return;
            if ((_direction == Direction.Up && dir == Direction.Down) ||
                (_direction == Direction.Down && dir == Direction.Up) ||
                (_direction == Direction.Left && dir == Direction.Right) ||
                (_direction == Direction.Right && dir == Direction.Left))
                return;
            _nextDirection = dir;
        }

        private void Tick()
        {
            if (_gameOver)
                return;

            _direction = _nextDirection;

            var head = _snake[0];
            var newHead = _direction switch
            {
                Direction.Up => (X: head.X, Y: head.Y - 1),
                Direction.Down => (X: head.X, Y: head.Y + 1),
                Direction.Left => (X: head.X - 1, Y: head.Y),
                Direction.Right => (X: head.X + 1, Y: head.Y),
                _ => head,
            };

            if (newHead.X < 0 || newHead.X >= GridSize || newHead.Y < 0 || newHead.Y >= GridSize)
            {
                _gameOver = true;
                _audio.PlayGlobal(new SoundPathSpecifier("/Audio/Effects/Arcade/gameover.ogg"), Filter.Local(), false, AudioParams.Default.WithVolume(-4f));
                return;
            }

            if (_snake.Contains(newHead))
            {
                _gameOver = true;
                _audio.PlayGlobal(new SoundPathSpecifier("/Audio/Effects/Arcade/gameover.ogg"), Filter.Local(), false, AudioParams.Default.WithVolume(-4f));
                return;
            }

            _snake.Insert(0, newHead);

            if (newHead == _food)
            {
                _score++;
                OnScoreChanged?.Invoke(_score);
                _audio.PlayGlobal(new SoundPathSpecifier("/Audio/Effects/Arcade/player_charge.ogg"), Filter.Local(), false, AudioParams.Default.WithVolume(-4f));
                SpawnFood();
            }
            else
            {
                _snake.RemoveAt(_snake.Count - 1);
            }
        }

        private void SpawnFood()
        {
            var freeCells = new List<(int X, int Y)>();
            for (var x = 0; x < GridSize; x++)
            for (var y = 0; y < GridSize; y++)
            {
                if (!_snake.Contains((x, y)))
                    freeCells.Add((x, y));
            }
            if (freeCells.Count > 0)
                _food = freeCells[_random.Next(freeCells.Count)];
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            var now = _timing.RealTime;
            var elapsed = (now - _lastTick).TotalSeconds;

            if (elapsed >= TickInterval)
            {
                Tick();
                _lastTick = now;
            }

            DrawBoard(handle);
        }

        private void DrawBoard(DrawingHandleScreen handle)
        {
            var size = PixelSize;
            var available = Math.Min(size.X, size.Y);
            var cellSize = available / GridSize;
            var boardPixel = cellSize * GridSize;
            var offsetX = (size.X - boardPixel) / 2;
            var offsetY = (size.Y - boardPixel) / 2;

            handle.DrawRect(
                new UIBox2(offsetX, offsetY, offsetX + boardPixel, offsetY + boardPixel),
                Color.FromHex("#111111"));

            for (var x = 0; x < GridSize; x++)
            {
                for (var y = 0; y < GridSize; y++)
                {
                    var rect = new UIBox2(
                        offsetX + x * cellSize,
                        offsetY + y * cellSize,
                        offsetX + (x + 1) * cellSize,
                        offsetY + (y + 1) * cellSize);

                    if ((x + y) % 2 == 0)
                        handle.DrawRect(rect, Color.FromHex("#1a1a2e"));
                }
            }

            foreach (var (segX, segY) in _snake)
            {
                var rect = new UIBox2(
                    offsetX + segX * cellSize,
                    offsetY + segY * cellSize,
                    offsetX + (segX + 1) * cellSize,
                    offsetY + (segY + 1) * cellSize);

                handle.DrawRect(rect, Color.FromHex("#00AA44"));

                if (segX == _snake[0].X && segY == _snake[0].Y)
                {
                    var inner = new UIBox2(
                        rect.Left + 2, rect.Top + 2,
                        rect.Right - 2, rect.Bottom - 2);
                    handle.DrawRect(inner, Color.FromHex("#00FF88"));
                }
            }

            {
                var rect = new UIBox2(
                    offsetX + _food.X * cellSize,
                    offsetY + _food.Y * cellSize,
                    offsetX + (_food.X + 1) * cellSize,
                    offsetY + (_food.Y + 1) * cellSize);

                handle.DrawRect(rect, Color.FromHex("#FF4444"));
            }

            if (_gameOver)
            {
                handle.DrawRect(
                    new UIBox2(offsetX, offsetY, offsetX + boardPixel, offsetY + boardPixel),
                    Color.FromHex("#00000088"));
            }
        }
    }
}
