- type: job
  id: OperatorGS
  name: job-name-OperatorGS
  description: job-description-OperatorGS
  playTimeTracker: JobOperatorGS
  whitelisted: True
  weight: 20
  startingGear: CentcomOperatorGear
  icon: "JobIconNanotrasen"
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune
    - type: ZombieImmune
    - type: NpcFactionMember
      factions:
      - CentralCommand
    - type: Skill
      group: ALL
  supervisors: job-supervisors-centcom-administrator
