- type: department
  id: NKVB
  name: department-NKVB
  description: department-NKVB-description
  color: "#ad4040"
  roles:
  - Politkom
  - Politruk
  - BlueShieldOfficer
  weight: 130

- type: department
  id: SoyuzGeneralStaff
  name: department-SoyuzGeneralStaff
  description: department-SoyuzGeneralStaff-description
  color: "#ad4040"
  roles:
  - OperatorGS
  - OfficerGS
  weight: 300
