- type: entity
  parent: BoxCardboard
  id: BoxSurvival
  name: survival box
  description: It's a box with basic internals inside.
  suffix: Standard
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskBreath
        - id: EmergencyOxygenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodSnackNutribrick
        - id: DrinkWaterBottleFull
  - type: Sprite
    layers:
    - state: internals
    - state: emergencytank

# DS14-Start
- type: entity
  parent: BoxBase
  id: BoxCardboardERT
  name: cardboard box
  description: A cardboard box for storing things.
  suffix: ERT
  components:
  - type: Item
    size: Large
    shape:
    - 0,0,2,1
  - type: Storage
    maxItemSize: Small
    grid:
    - 0,0,3,3
  - type: Sprite
    layers:
    - state: internals
    - state: emergencytank
  - type: StorageFill
    contents:
      - id: ClothingMaskGasERT
      - id: FoodSnackNutribrickOpen
      - id: DrinkMREFlask
      - id: EmergencyMedipen
      - id: AirlossAutoInjector
      - id: HandHeldMassScanner
      - id: Flare
      - id: Flare
      - id: Flash
      - id: DoubleEmergencyOxygenTankFilled

- type: startingGear
  id: ERTLeaderGearAmber
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackRIGERTLeader
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudERT
    ears: ClothingHeadsetCentCom
    neck: ClothingNeckMantleERTLeader
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBulletproof
    suitstorage: WeaponDisablerSMG
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetERTLeader
    id: ERTLeaderPDA
    belt: ClothingBeltMilitaryWebbingERT
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: FlashlightSeclite
  storage:
    back:
    - ERTloadoutAmberPrimary
    - ERTloadoutAmberSecondary
    - PinpointerNuclear
    - BoxCardboardERT
    - JawsOfLife
    - PortableCameraMonitor
    - CriminalRecordsMonitor
    - HandheldCrewMonitor

- type: entity
  parent: BoxSurvival
  id: BoxSurvivalNitrogen
  suffix: Standard N2
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskBreath
        - id: EmergencyNitrogenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodSnackNutribrick
        - id: DrinkWaterBottleFull
  - type: Sprite
    layers:
    - state: internals
    - state: nitrogentank
  - type: Label
    currentLabel: reagent-name-nitrogen

- type: startingGear
  id: ERTLeaderGearRed
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    eyes: ClothingEyesHudERTGamma
    ears: ClothingHeadsetCentCom
    head: ClothingHeadHatERTLeaderBeret
    neck: ClothingNeckMantleERTLeader
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTRedLeader
    suitstorage: JetpackSecurityFilled
    shoes: ADTClothingShoesBootsMagERT
    id: ERTLeaderRedPDA
    belt: ClothingBeltMilitaryWebbingERT
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: DoorRemoteCustom
  storage:
    back:
    - ERTloadoutRedPrimary
    - ERTloadoutRedSecondary
    - BoxCardboardERT
    - PinpointerNuclear
    - CrowbarRed
    - WeaponDisabler

- type: entity
  parent: BoxSurvival
  id: BoxSurvivalMoth
  suffix: Standart for moths
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskBreath
        - id: EmergencyOxygenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodSnackFabricbrick
        - id: DrinkWaterBottleFull

- type: startingGear
  id: ERTLeaderGearGamma
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    eyes: ClothingEyesHudERTGamma
    ears: ClothingHeadsetCentCom
    head: ClothingHeadHatERTLeaderBeret
    neck: ClothingNeckMantleERTLeader
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    suitstorage: JetpackVoidFilled
    shoes: ADTClothingShoesBootsMagERT
    id: ERTLeaderGammaPDA
    belt: ClothingBeltMilitaryWebbingERTGamma
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: DoorRemoteCustom
  storage:
    back:
    - ERTloadoutGammaPrimary
    - ERTloadoutGammaSecondary
    - BoxCardboardERT
    - PinpointerNuclear
    - CrowbarRed
    - WeaponDisabler

- type: entity
  parent: BoxSurvival
  id: BoxSurvivalRobotNonBreather
  suffix: Standard for robot non breathers
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingHeadHatWelding
        - id: CableApcStack5
        - id: CrowbarRed
        - id: Flare
        - id: DrinkWaterBottleFull

- type: startingGear
  id: ERTSecurityGearAmber
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackRIGERTSecurity
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudERT
    ears: ClothingHeadsetCentCom
    neck: ClothingNeckBodyCamera
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBulletproof
    suitstorage: WeaponDisablerSMG
    shoes: ClothingShoesBootsJackSecFilled
    head: ClothingHeadHelmetERTSecurity
    id: ERTSecurityPDA
    belt: ClothingBeltMilitaryWebbingERT
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: FlashlightSeclite
  storage:
    back:
    - ERTloadoutAmberPrimary
    - ERTloadoutAmberSecondary
    - PinpointerNuclear
    - BoxCardboardERT
    - JawsOfLife
    - PortableCameraMonitor
    - CriminalRecordsMonitor
    - HandheldCrewMonitor
    - TelescopicShield
    - TelescopicShield

- type: entity
  parent: BoxSurvivalEngineering
  id: BoxSurvivalEngineeringNitrogen
  suffix: Extended N2
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskBreath
        - id: ExtendedEmergencyNitrogenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodSnackNutribrick
        - id: DrinkWaterBottleFull
  - type: Sprite
    layers:
    - state: internals
    - state: nitrogentank
  - type: Label
    currentLabel: reagent-name-nitrogen

- type: startingGear
  id: ERTSecurityGearRed
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    eyes: ClothingEyesHudERT
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTRedSecurity
    suitstorage: JetpackSecurityFilled
    shoes: ADTClothingShoesBootsMagERT
    id: ERTSecurityRedPDA
    belt: ClothingBeltMilitaryWebbingERT
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: TelescopicShield
  storage:
    back:
    - ERTloadoutRedPrimary
    - ERTloadoutRedSecondary
    - BoxCardboardERT
    - CrowbarRed
    - PinpointerNuclear
    - WeaponDisabler

- type: entity
  parent: BoxSurvivalEngineering
  id: BoxSurvivalEngineeringMoth
  suffix: Extended moth
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskBreath
        - id: ExtendedEmergencyOxygenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodSnackFabricbrick
        - id: DrinkWaterBottleFull

- type: startingGear
  id: ERTSecurityGearGamma
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    eyes: ClothingEyesHudERTGamma
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    suitstorage: JetpackVoidFilled
    shoes: ADTClothingShoesBootsMagERT
    id: ERTSecurityGammaPDA
    belt: ClothingBeltMilitaryWebbingERTGamma
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: TelescopicShield
  storage:
    back:
    - ERTloadoutGammaPrimary
    - ERTloadoutGammaSecondary
    - BoxCardboardERT
    - CrowbarRed
    - PinpointerNuclear
    - WeaponDisabler

- type: entity
  parent: BoxSurvivalSecurity
  id: BoxSurvivalSecurityNitrogen
  suffix: Security N2
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskGasSecurity
        - id: EmergencyNitrogenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodSnackNutribrick
        - id: DrinkWaterBottleFull
  - type: Sprite
    layers:
    - state: internals
    - state: nitrogentank
  - type: Label
    currentLabel: reagent-name-nitrogen

- type: startingGear
  id: ERTMedicalGearAmber
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackRIGERTMedic
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudERT
    ears: ClothingHeadsetCentCom
    neck: ClothingNeckBodyCamera
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBulletproof
    suitstorage: WeaponDisablerSMG
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHelmetERTMedic
    id: ERTMedicPDA
    belt: ClothingBeltMedicalFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: FlashlightSeclite
  storage:
    back:
    - ERTloadoutAmberPrimary
    - ERTloadoutAmberSecondary
    - PinpointerNuclear
    - BoxCardboardERT
    - JawsOfLife
    - PortableCameraMonitor
    - CriminalRecordsMonitor
    - HandheldCrewMonitor
    - DefibrillatorCompact
    - ADTCombatHypo
    - ChemistryBottleOmnizine
    - ChemistryBottleEpinephrine

- type: entity
  parent: BoxSurvivalSecurity
  id: BoxSurvivalSecurityMoth
  suffix: Security moth
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskGasSecurity
        - id: EmergencyOxygenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodSnackFabricbrick
        - id: DrinkWaterBottleFull

- type: startingGear
  id: ERTMedicalGearRed
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    eyes: ClothingEyesHudERTGamma
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTRedMedic
    suitstorage: JetpackSecurityFilled
    shoes: ADTClothingShoesBootsMagERT
    id: ERTMedicRedPDA
    belt: ClothingBeltMilitaryWebbingERTMed
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ADTCombatHypo
  storage:
    back:
    - ERTloadoutRedPrimary
    - ERTloadoutRedSecondary
    - BoxCardboardERT
    - DefibrillatorCompact
    - PinpointerNuclear
    - JugDexPlusSaline
    - CrowbarRed
    - ChemistryBottleOmnizine
    - ChemistryBottleOmnizine
    - ChemistryBottleBruizine
    - ChemistryBottlePyrazine

- type: entity
  parent: BoxSurvivalMedical
  id: BoxSurvivalMedicalNitrogen
  suffix: Medical N2
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskBreathMedical
        - id: EmergencyNitrogenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodSnackNutribrick
        - id: DrinkWaterBottleFull
  - type: Sprite
    layers:
    - state: internals
    - state: nitrogentank
  - type: Label
    currentLabel: reagent-name-nitrogen

- type: startingGear
  id: ERTMedicalGearGamma
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    eyes: ClothingEyesHudERTGamma
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTMedical
    suitstorage: JetpackVoidFilled
    shoes: ADTClothingShoesBootsMagERT
    id: ERTMedicGammaPDA
    belt: ClothingBeltMilitaryWebbingERTMed
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ADTCombatHypo
  storage:
    back:
    - ERTloadoutGammaPrimary
    - ERTloadoutGammaSecondary
    - BoxCardboardERT
    - DefibrillatorCompact
    - PinpointerNuclear
    - JugTheCircleOmnizine
    - JugDexPlusSaline
    - CrowbarRed

- type: entity
  parent: BoxSurvivalMedical
  id: BoxSurvivalMedicalMoth
  suffix: Medical moth
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskBreathMedical
        - id: EmergencyOxygenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodSnackFabricbrick
        - id: DrinkWaterBottleFull

- type: startingGear
  id: ERTEngineerGearAmber
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackRIGERTEngineer
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudAdvanced
    ears: ClothingHeadsetCentCom
    neck: ClothingNeckBodyCamera
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBulletproof
    suitstorage: JetpackMiniFilled
    shoes: ClothingShoesBootsMag
    head: ClothingHeadHelmetERTEngineer
    id: ERTEngineerPDA
    belt: ClothingBeltMilitaryWebbingERT
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: FlashlightSeclite
  storage:
    back:
    - ERTloadoutAmberPrimary
    - ERTloadoutAmberSecondary
    - PinpointerNuclear
    - BoxCardboardERT
    - PortableCameraMonitor
    - CriminalRecordsMonitor
    - HandheldCrewMonitor
    - Omnitool
    - WelderIndustrialAdvanced
    - RCD
    - RCDAmmo
    - RCDAmmo

- type: entity
  parent: BoxHug
  id: BoxHugNitrogen
  suffix: Emergency N2
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskBreath
        - id: EmergencyNitrogenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodSnackNutribrick
        - id: DrinkWaterBottleFull
  - type: Label
    currentLabel: reagent-name-nitrogen

- type: startingGear
  id: ERTEngineerGearRed
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    eyes: ClothingEyesHudERT
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTRedEngineer
    suitstorage: JetpackSecurityFilled
    shoes: ADTClothingShoesBootsMagERT
    id: ERTEngineerRedPDA
    belt: ClothingBeltChiefEngineerFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: WeaponDisabler
  storage:
    back:
    - ERTloadoutRedPrimary
    - ERTloadoutRedSecondary
    - BoxCardboardERT
    - BoxC4ERT
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo

- type: entity
  parent: BoxHug
  id: BoxHugMoth
  suffix: Emergency moth
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskBreath
        - id: EmergencyFunnyOxygenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodSnackFabricbrick
        - id: DrinkWaterBottleFull

- type: startingGear
  id: ERTEngineerGearGamma
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    eyes: ClothingEyesHudERTGamma
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    suitstorage: JetpackVoidFilled
    shoes: ADTClothingShoesBootsMagERT
    id: ERTEngineerGammaPDA
    belt: ClothingBeltChiefEngineerFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: WeaponDisabler
  storage:
    back:
    - ERTloadoutGammaPrimary
    - ERTloadoutGammaSecondary
    - BoxCardboardERT
    - BoxC4ERT
    - RCDRecharging
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - PinpointerNuclear

- type: entity
  parent: BoxSurvivalNitrogen
  id: BoxMimeNitrogen
  suffix: Mime, Emergency N2
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskBreath
        - id: EmergencyNitrogenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodBreadNutriBatard
        - id: DrinkWaterBottleFull
  - type: Sprite
    layers:
    - state: internals
    - state: nitrogentank
  - type: Label
    currentLabel: reagent-name-nitrogen

- type: startingGear
  id: ERTJanitorGearAmber
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackRIGERTJanitor
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudERT
    ears: ClothingHeadsetCentCom
    neck: ClothingNeckBodyCamera
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBulletproof
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetERTJanitor
    id: ERTJanitorPDA
    belt: ClothingBeltJanitorFilledERT
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: FlashlightSeclite
  storage:
    back:
    - ERTloadoutAmberPrimary
    - ERTloadoutAmberSecondary
    - BoxCardboardERT
    - BoxLightMixed
    - MopItem
    - BoxCleanerGrenades
    - JawsOfLife
    - PinpointerNuclear

- type: entity
  parent: BoxSurvival
  id: BoxMimeMoth
  suffix: Mime, Emergency moth
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskBreath
        - id: EmergencyOxygenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodBreadCottonNutriBatard
        - id: DrinkWaterBottleFull

- type: startingGear
  id: ERTJanitorGearRed
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    eyes: ClothingEyesHudERTGamma
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTRedJanitor
    suitstorage: JetpackSecurityFilled
    shoes: ADTClothingShoesBootsMagERT
    id: ERTJanitorRedPDA
    belt: ClothingBeltJanitorFilledERT
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: WeaponDisabler
  storage:
    back:
    - ERTloadoutRedPrimary
    - ERTloadoutRedSecondary
    - BoxCardboardERT
    - BoxLightMixed
    - AdvMopItem
    - BoxCleanerGrenades
    - CrowbarRed
    - PinpointerNuclear

- type: entity
  parent: BoxSurvivalSyndicate
  id: BoxSurvivalSyndicateNitrogen
  suffix: Syndicate N2
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase: !type:AllSelector
        children:
        - id: ClothingMaskGasSyndicate
        - id: ExtendedEmergencyNitrogenTankFilled
        - id: EmergencyMedipen
        - id: Flare
        - id: FoodSnackNutribrick
  - type: Sprite
    layers:
    - state: internals
    - state: nitrogentank
  - type: Label
    currentLabel: reagent-name-nitrogen

- type: startingGear
  id: ERTJanitorGearGamma
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    eyes: ClothingEyesHudERTGamma
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTJanitor
    suitstorage: JetpackVoidFilled
    shoes: ADTClothingShoesBootsMagERT
    id: ERTJanitorGammaPDA
    belt: ClothingBeltJanitorFilledERT
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: WeaponDisabler
  storage:
    back:
    - ERTloadoutGammaPrimary
    - ERTloadoutGammaSecondary
    - BoxCardboardERT
    - WeaponLauncherHydra
    - BoxLightMixed
    - AdvMopItem
    - BoxGrenadeCleanade
    - CrowbarRed
    - PinpointerNuclear
