# Tier 2

- type: technology
  id: SilverAmmo
  name: research-technology-silver-ammo
  icon:
    sprite: Objects/Materials/ingots.rsi
    state: silver
  discipline: Security
  tier: 1
  cost: 11000
  recipeUnlocks:
  - MagazineBox357Silver
  - MagazineBoxLightestRifleSilver
  - MagazineBoxRifleSilver
  - MagazineBoxLightRifleSilver
  - MagazineBoxPistolSilver
  - BoxLethalshotSilver
  - MagazinePistolSilver
  - MagazineLightRifleSilver
  - MagazineRifleSilver
  - MagazineShotgunSilver
  - SpeedLoaderMagnumSilver
  - MagazinePistolSubMachineGunSilver

- type: technology
  id: Implanters
  name: research-technology-implants
  icon:
    sprite: Objects/Specific/Medical/syndi_implanter.rsi
    state: implanter1
  discipline: Security
  tier: 2
  cost: 10000
  recipeUnlocks:
  - EyeSocketImplanter
  - TrackingImplanter
  - MindShieldImplanter

- type: technology
  id:  ArmedTechFab
  name: research-technology-armed-tech-fab-technology
  icon:
    sprite: Structures/Machines/techfab.rsi
    state: icon_armed
  discipline: Security
  tier: 2
  cost: 12500
  recipeUnlocks:
  - ArmedTechFabCircuitboard

- type: technology
  id: PosketDefenseWeaponry
  name: research-technology-pistols
  icon:
    sprite: Objects/Weapons/Guns/Pistols/mk58.rsi
    state: icon
  discipline: Security
  tier: 2
  cost: 10000
  recipeUnlocks:
  - WeaponPistolMk58
  - WeaponRevolverPythonSoyuz

- type: technology
  id: BallisticsShotguns
  name: research-technology-shotguns-soyuz
  icon:
    sprite: Objects/Weapons/Guns/Shotguns/pump.rsi
    state: icon
  discipline: Security
  tier: 2
  cost: 12000
  recipeUnlocks:
  - WeaponShotgunKammerer
  - WeaponShotgunEnforcer

- type: technology
  id: BallisticsAutomaticWeapons
  name: research-technology-automatic-weapons
  icon:
    sprite: Objects/Weapons/Guns/Rifles/ak.rsi
    state: icon
  discipline: Security
  tier: 2
  cost: 15000
  recipeUnlocks:
  - WeaponRifleAkSoyuz
  - WeaponSubMachineGunDrozd

- type: technology
  id: SecurityAmmoTungsten
  name: research-technology-ammo-tungsten-technology
  icon:
    sprite: _DeadSpace/Objects/Weapons/Guns/Ammunition/Boxes/light_rifle.rsi
    state: icon_tungsten
  discipline: Security
  tier: 2
  cost: 15000
  recipeUnlocks:
  - MagazineBoxRifleTungsten
  - MagazineBoxLightRifleTungsten
  - MagazineBoxMagnumTungsten
  - MagazineBoxPistolTungsten
  - SpeedLoaderMagnumTungsten
  - MagazineLightRifleTungsten
  - MagazineRifleTungsten
  - MagazinePistolSubMachineGunTungsten
  - MagazinePistolTungsten
  - MagazineLightRifleVSSTungsten
  - MagazineLightRifleAsValTungsten

- type: technology
  id: SecurityMagazine
  name: research-technology-ammo-magazine
  icon:
    sprite: _DeadSpace/_Soyuz/Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/asval.rsi
    state: icon
  discipline: Security
  tier: 2
  cost: 15000
  recipeUnlocks:
  - MagazineLightRifleAsVal
  - MagazineLightRifleAsValEmpty
  - MagazineLightRifleAsValPractice
  - MagazineLightRifleAsValUranium
  - MagazineLightRifleAsValIncendiary
  - MagazineLightRifleVSS
  - MagazineLightRifleVSSEmpty
  - MagazineLightRifleVSSPractice
  - MagazineLightRifleVSSUranium
  - MagazineLightRifleVSSIncendiary

- type: technology
  id: SecurityPoliceBetaTechnology
  name: research-technology-police-beta-technology
  icon:
    sprite: _DeadSpace/_Soyuz/Clothing/OuterClothing/Hardsuits/beta.rsi
    state: icon
  discipline: Security
  tier: 2
  cost: 12500
  recipeUnlocks:
  - PoliceBetaLegs
  - PoliceBetaHead
  - PoliceBetaComp
  - PoliceBetaBody

# Tier 3

- type: technology
  id: AdvancedBallisticsShotguns
  name: research-technology-advanced-shotguns
  icon:
    sprite: _DeadSpace/_Soyuz/Objects/Weapons/Guns/Shotguns/saiga.rsi
    state: icon
  discipline: Security
  tier: 3
  cost: 15000
  recipeUnlocks:
  - WeaponShotgunSaiga

- type: technology
  id: AdvancedBallisticsAutomaticWeapons
  name: research-technology-advanced-automatic-weapons
  icon:
    sprite: _DeadSpace/_Soyuz/Objects/Weapons/Guns/Rifles/asval.rsi
    state: icon
  discipline: Security
  tier: 3
  cost: 20000
  recipeUnlocks:
  - WeaponRifleAKMCY
  - WeaponRifleAsVal
  - WeaponRifleVSS

- type: technology
  id: AdvancedShotgunMagazine
  name: research-technology-advanced-shotgun-ammo-magazine
  icon:
    sprite: _DeadSpace/_Soyuz/Objects/Weapons/Guns/Ammunition/Magazine/Shotgun/mag.rsi
    state: base
  discipline: Security
  tier: 3
  cost: 17500
  recipeUnlocks:
  - MagazineShotgunNew
  - MagazineShotgunNewEmpty
  - MagazineShotgunDrum
  - MagazineShotgunDrumEmpty

- type: technology
  id: AdvancedSecurityMagazine
  name: research-technology-advanced-ammo-magazine
  icon:
    sprite: _DeadSpace/_Soyuz/Objects/Weapons/Guns/Ammunition/Magazine/Magnum/ash_mag.rsi
    state: icon
  discipline: Security
  tier: 3
  cost: 17500
  recipeUnlocks:
  - MagazineRifleASH
  - MagazineRifleASHEmpty

- type: technology
  id: BallisticsLargeCaliberWeapons
  name: research-technology-ballistics-large-caliber-weapons
  icon:
    sprite: _DeadSpace/_Soyuz/Objects/Weapons/Guns/Rifles/ash.rsi
    state: icon
  discipline: Security
  tier: 3
  cost: 50000
  recipeUnlocks:
  - WeaponRifleASH12
