# Tier 1

# Tier 2
- type: technology
  id: PolaroidCamera
  name: research-technology-experimental-camera
  icon:
    sprite: Objects/Devices/travel_camera.rsi
    state: icon
  discipline: Service
  tier: 1
  cost: 7500
  recipeUnlocks:
  - PolaroidCamera
  - PolaroidCartridge

# Tier 3