using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;

namespace Content.Client.MediaWiki.UI;

[GenerateTypedNameReferences]
public sealed partial class MediaWikiBookWindow : FancyWindow
{
    private readonly MediaWikiRenderer _renderer = new();

    public MediaWikiBookWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetDocument(string title, string source)
    {
        Title = title;
        Scroll.SetScrollValue(default);
        ContentContainer.RemoveAllChildren();
        _renderer.Render(ContentContainer, source);
    }
}
