using System;
using System.Numerics;
using Content.Client.Guidebook.RichText;
using Content.Client.UserInterface.ControlExtensions;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Maths;

namespace Content.Client.MediaWiki.UI;

[GenerateTypedNameReferences]
public sealed partial class MediaWikiBookWindow : FancyWindow, ILinkClickHandler
{
    private static readonly Vector2 OpenSizeScale = new(0.94f, 0.88f);
    private static readonly Vector2 ScreenMargin = new(64f, 64f);

    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IUriOpener _uri = default!;

    private readonly MediaWikiRenderer _renderer = new();
    private string _page = string.Empty;

    public MediaWikiBookWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void Opened()
    {
        base.Opened();

        if (Parent == null)
            return;

        var preferredSize = Parent.Size * OpenSizeScale;
        var maxVisibleSize = Vector2.Max(Vector2.Zero, Parent.Size - ScreenMargin);

        SetSize = Vector2.Min(Vector2.Max(preferredSize, MinSize), maxVisibleSize);
        Measure(Vector2Helpers.Infinity);
        RecenterWindow(new Vector2(0.5f, 0.5f));
    }

    public void SetDocument(string title, string page, string source)
    {
        Title = title;
        _page = page;
        Scroll.SetScrollValue(default);
        ContentContainer.RemoveAllChildren();
        _renderer.Render(ContentContainer, source);
    }

    public void HandleClick(string link)
    {
        if (TryResolveAnchor(link, out var anchor) && ScrollToAnchor(anchor))
            return;

        if (TryResolveWikiUri(link, out var uri))
            _uri.OpenUri(uri);
    }

    private bool ScrollToAnchor(string anchor)
    {
        var control = FindAnchorControl(ContentContainer, anchor);
        if (control == null)
            return false;

        UserInterfaceManager.DeferAction(() =>
        {
            if (control.GetControlScrollPosition() is not { } position)
                return;

            Scroll.HScrollTarget = position.X;
            Scroll.VScrollTarget = position.Y;
        });

        return true;
    }

    private static Control? FindAnchorControl(Control root, string anchor)
    {
        if (string.Equals(NormalizeAnchor(root.Name), anchor, StringComparison.OrdinalIgnoreCase))
            return root;

        foreach (var child in root.Children)
        {
            var found = FindAnchorControl(child, anchor);
            if (found != null)
                return found;
        }

        return null;
    }

    private bool TryResolveAnchor(string link, out string anchor)
    {
        anchor = string.Empty;

        if (string.IsNullOrWhiteSpace(link))
            return false;

        link = link.Trim();

        if (link.StartsWith('#'))
        {
            anchor = NormalizeAnchor(link[1..]);
            return anchor.Length > 0;
        }

        var hashIndex = link.IndexOf('#');
        if (hashIndex <= 0 || hashIndex >= link.Length - 1)
            return false;

        var page = NormalizePage(link[..hashIndex]);
        if (!string.Equals(page, NormalizePage(_page), StringComparison.OrdinalIgnoreCase))
            return false;

        anchor = NormalizeAnchor(link[(hashIndex + 1)..]);
        return anchor.Length > 0;
    }

    private bool TryResolveWikiUri(string link, out string uri)
    {
        uri = string.Empty;

        if (string.IsNullOrWhiteSpace(link))
            return false;

        link = link.Trim();

        if (IsHttpUri(link))
        {
            uri = link;
            return true;
        }

        var baseUri = _cfg.GetCVar(CCVars.InfoLinksWiki);
        if (string.IsNullOrWhiteSpace(baseUri))
            baseUri = "https://wiki.deadspace14.net";

        var target = link;
        string? fragment = null;

        var hashIndex = target.IndexOf('#');
        if (hashIndex >= 0)
        {
            fragment = NormalizeAnchor(target[(hashIndex + 1)..]);
            target = target[..hashIndex];
        }

        target = target.Trim().Replace(' ', '_');
        if (target.Length == 0)
            return false;

        var full = $"{baseUri.TrimEnd('/')}/{Uri.EscapeDataString(target)}";
        if (!string.IsNullOrWhiteSpace(fragment))
            full += $"#{Uri.EscapeDataString(fragment.Replace(' ', '_'))}";

        if (!IsHttpUri(full))
            return false;

        uri = full;
        return true;
    }

    private static bool IsHttpUri(string uri)
    {
        try
        {
            var parsed = new Uri(uri);
            return parsed.IsAbsoluteUri
                && (parsed.Scheme == Uri.UriSchemeHttp || parsed.Scheme == Uri.UriSchemeHttps);
        }
        catch
        {
            return false;
        }
    }

    private static string NormalizePage(string? page)
    {
        if (string.IsNullOrWhiteSpace(page))
            return string.Empty;

        return page.Trim().Replace(' ', '_');
    }

    private static string NormalizeAnchor(string? anchor)
    {
        if (string.IsNullOrWhiteSpace(anchor))
            return string.Empty;

        anchor = anchor.Trim().Replace('_', ' ');
        return string.Join(" ", anchor.Split((char[]?) null, StringSplitOptions.RemoveEmptyEntries));
    }
}
