using System;
using System.Globalization;
using System.Text;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.EnergySeller;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Shared.Localization;

namespace Content.Client.DeadSpace.EnergySeller;

[GenerateTypedNameReferences]
public sealed partial class EnergySellerUserInterface : FancyWindow
{
    public event Action<int, int>? OnConfirmSellLimit;
    public event Action<int, int>? OnConfirmSpeedCharge;

    private bool _updatingControls;

    public EnergySellerUserInterface()
    {
        RobustXamlLoader.Load(this);

        // Подписка на изменения слайдеров для синхронизации с лейблами
        ChargeSpeedSlider.OnValueChanged += args => UpdateSpeedChargeLabel();
        MaxChargeSlider.OnValueChanged += args => UpdateSellLimitLabel();

        ChargeSpeedLineEdit.OnTextEntered += _ => ConfirmSpeedCharge();
        MaxChargeLineEdit.OnTextEntered += _ => ConfirmSellLimit();

        SpeedChargeConfirm.OnPressed += _ => ConfirmSpeedCharge();
        SellLimitConfirm.OnPressed += _ => ConfirmSellLimit();
    }

    public void UpdateState(BoundUserInterfaceState state)
    {
        var castState = (EnergySellerBoundUserInterfaceState)state;

        _updatingControls = true;

        ChargeSpeedSlider.MaxValue = castState.MaxChargeRate;
        ChargeSpeedSlider.SetValueWithoutEvent(castState.NowChargeRate);
        SetValueLabel(ChargeSpeedValue, castState.NowChargeRate);
        SetValueLabel(ChargeSpeedMaxLabel, castState.MaxChargeRate);

        MaxChargeSlider.MaxValue = castState.MaxLimit;
        MaxChargeSlider.SetValueWithoutEvent(castState.NowLimit);
        SetValueLabel(MaxChargeMaxLabel, castState.MaxLimit);
        SetValueLabel(LimitSellValue, castState.NowLimit);

        _updatingControls = false;
    }

    private void ConfirmSpeedCharge()
    {
        var sliderValue = GetSliderValue(ChargeSpeedSlider);
        if (TryParsePower(ChargeSpeedLineEdit.Text, out var parsedValue))
        {
            OnConfirmSpeedCharge?.Invoke(sliderValue, parsedValue);
        }
        else
        {
            OnConfirmSpeedCharge?.Invoke(sliderValue, sliderValue);
        }
        ChargeSpeedLineEdit.Text = "";
    }

    private void ConfirmSellLimit()
    {
        var sliderValue = GetSliderValue(MaxChargeSlider);
        if (TryParsePower(MaxChargeLineEdit.Text, out var parsedValue))
        {
            OnConfirmSellLimit?.Invoke(sliderValue, parsedValue);
        }
        else
        {
            OnConfirmSellLimit?.Invoke(sliderValue, sliderValue);
        }
        MaxChargeLineEdit.Text = "";
    }

    private void UpdateSpeedChargeLabel()
    {
        if (_updatingControls) return;
        SetValueLabel(ChargeSpeedValue, GetSliderValue(ChargeSpeedSlider));
    }

    private void UpdateSellLimitLabel()
    {
        if (_updatingControls) return;
        SetValueLabel(LimitSellValue, GetSliderValue(MaxChargeSlider));
    }

    private static int GetSliderValue(Slider slider)
    {
        return (int)Math.Round(slider.Value, MidpointRounding.AwayFromZero);
    }

    private static void SetValueLabel(Label label, int value)
    {
        label.Text = Loc.GetString("energy-seller-ui-watts", ("value", FormatInputValue(value)));
    }

    private static string FormatInputValue(int value)
    {
        return value.ToString("N0", CultureInfo.InvariantCulture).Replace(",", " ");
    }

    private static bool TryParsePower(string text, out int value)
    {
        value = 0;

        if (string.IsNullOrWhiteSpace(text))
            return false;

        var digits = new StringBuilder(text.Length);
        foreach (var character in text)
        {
            if (char.IsDigit(character))
                digits.Append(character);
        }

        return digits.Length > 0 && int.TryParse(digits.ToString(), NumberStyles.Integer, CultureInfo.InvariantCulture, out value);
    }
}
