using System.Numerics;
using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.DeadSpace.Soyuz.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class USSPChatEmojiPopup : DefaultWindow
{
    private const int EmojiButtonSize = 40;

    public Action<string>? OnEmojiSelected;

    private static readonly string[] Emojis =
    [
        ":)", ":-)", ":]", "(:", "(-:", ":}", "=)", "=]", ":^)", "^_^", "^^",
        ":D", ":-D", "=D", "xD", "XD", "X-D", "8D", "B^D", "c:",
        ";)", ";-)", "*-)", "*)", ";]", ";^)", ";D",
        ":P", ":-P", ":p", ":-p", "=P", "=p", "xP", "XP", ":b", ":-b",
        ":O", ":-O", ":o", ":-o", "=O", "D:", "D-:", "DX", "D8", ">:O",
        ":(", ":-(", ":[", ":-[", ":{", ":-{", "=(", "= [", "):", ")-:",
        ":'(", ":'-(", ":,(", "T_T", "TT_TT", "Q_Q", ";_;", "D';", ":'D",
        ":|", ":-|", "=|", "-_-", "-.-", "._.", ":/", ":-/", ":\\", ":-\\",
        ":S", ":-S", ":s", ":-s", ":$", ":-$", ":#", ":-#", ":X", ":-X",
        ">:(", ">:-(", ">:)", ">:-)", "]:)", "}:-)", ">=(", ">=)", "D:<",
        ":3", ":-3", "=3", "x3", "X3", ":>", ":<", ":*", ":-*", "=*", "<3", "</3",
        "o7", "\\o", "\\o/", "o/", "\\\\o//", "0/", "\\0/", "07",
        "O_O", "o_o", "0_0", "O.o", "o.O", "o.O", "OvO", "@_@", "*_*", "+_+",
        "._", "__", "...", "..", "?", "!", "!?", "?!", "!!", "??",
        "<-", "->", "<->", "-->", "<--", "=>", "<=", "==>", "<==", "<=>",
        "^", "^^", "^^^", "v", "VV", "<", ">", "<<", ">>", "<3",
        "8)", "8-)", "B)", "B-)", "|;)", "|-O", "8|", "B|", "8-P", "B-P",
        ":@", ":-@", ">.<", "<.<", ">.>", "=/", "=\\", ":L", ":-L", ":7", ":-7"
    ];

    public USSPChatEmojiPopup()
    {
        RobustXamlLoader.Load(this);
        foreach (var emoji in Emojis)
        {
            EmojiContainer.AddChild(BuildEmojiButton(emoji));
        }
    }

    public void Show(Action<string> onSelect)
    {
        OnEmojiSelected = onSelect;
        OpenCentered();
    }

    private Button BuildEmojiButton(string emoji)
    {
        var button = new Button
        {
            Text = emoji,
            MinSize = new Vector2(EmojiButtonSize, EmojiButtonSize),
            HorizontalExpand = true
        };

        button.OnPressed += _ =>
        {
            OnEmojiSelected?.Invoke(emoji);
            Close();
        };

        return button;
    }
}
