using Content.Client.UserInterface.RichText;
using Content.Shared.DeadSpace.Soyuz.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.Soyuz.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class USSPChatMessageControl : Control
{
    private static readonly Type[] AllowedTags =
    [
        typeof(BoldItalicTag),
        typeof(BoldTag),
        typeof(BulletTag),
        typeof(ColorTag),
        typeof(HeadingTag),
        typeof(ItalicTag),
        typeof(MonoTag)
    ];

    public USSPChatMessageControl(ChatMessage message)
    {
        RobustXamlLoader.Load(this);
        MessageText.SetMessage(FormattedMessage.FromMarkupPermissive(message.Message), AllowedTags, null);
        SenderName.Text = message.SenderName;
        TimeLabel.Text = message.Timestamp.ToString(@"hh\:mm");
        ApplyMessageDirection(message);
        ApplyDeliveryState(message);
    }

    private void ApplyMessageDirection(ChatMessage message)
    {
        var alignment = message.IsOwnMessage ? HAlignment.Right : HAlignment.Left;
        MessageContainer.HorizontalAlignment = alignment;
        HeaderContainer.HorizontalAlignment = alignment;
    }

    private void ApplyDeliveryState(ChatMessage message)
    {
        if (!message.IsOwnMessage || message.Delivered)
            return;

        MessageText.ModulateSelfOverride = Color.Red;
    }
}
