using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Soyuz.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class USSPChatAddContactPopup : DefaultWindow
{
    private const int MaxContactIdLength = 5;
    private const int MaxContactNameLength = 9;

    public Action<string, string>? OnContactAdded;

    public USSPChatAddContactPopup()
    {
        RobustXamlLoader.Load(this);
        CancelButton.OnPressed += _ => Close();

        AddButton.OnPressed += _ => Submit();
        ContactNameInput.OnTextEntered += _ => Submit();
        ContactIdInput.OnTextEntered += _ => ContactNameInput.GrabKeyboardFocus();
    }

    private static string NormalizeContactId(string contactId)
    {
        var cleanedId = contactId.Trim().Replace(" ", "");
        if (!cleanedId.StartsWith("#") && cleanedId.All(char.IsDigit))
            return "#" + cleanedId;

        return cleanedId;
    }

    private void Submit()
    {
        if (!TryBuildContact(out var contactId, out var contactName))
            return;

        OnContactAdded?.Invoke(contactId, contactName);
        Close();
    }

    private bool TryBuildContact(out string contactId, out string contactName)
    {
        contactId = string.Empty;
        contactName = string.Empty;

        if (string.IsNullOrWhiteSpace(ContactIdInput.Text) || string.IsNullOrWhiteSpace(ContactNameInput.Text))
            return false;

        contactId = NormalizeContactId(Truncate(ContactIdInput.Text, MaxContactIdLength));
        contactName = Truncate(ContactNameInput.Text, MaxContactNameLength);
        return !string.IsNullOrWhiteSpace(contactId) && !string.IsNullOrWhiteSpace(contactName);
    }

    private static string Truncate(string value, int maxLength)
    {
        return value.Length <= maxLength ? value : value[..maxLength];
    }
}
