using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared.DeadSpace.Soyuz.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.DeadSpace.Soyuz.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class USSPChatUiFragment : BoxContainer
{
    private static readonly Color ChatHeaderPanelBackgroundColor = Color.FromHex("#131313");

    public Action? OpenAddContact;
    public Action? OpenDiscovery;
    public Action<bool>? SetVisibleInDiscovery;
    public Action<List<DiscoveryEntry>>? DiscoveryListReceived;
    public Action? OnMutePressed;
    public Action? OpenEmojiPicker;
    public Action<string>? SetActiveChat;
    public Action<string>? SendMessage;
    public Action<string>? EraseChat;
    public Action<string>? CloseChat;
    public Action<string>? LeaveChat;
    public Action? JoinGroup;
    public Action? CreateGroup;

    private USSPChatEmojiPopup? _emojiPopup;
    private bool _canSendMessages = true;
    public string? ActiveChatId;
    public Dictionary<string, ChatContact> Contacts = new();
    public Dictionary<string, ChatGroup> Groups = new();

    public USSPChatUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        ChatHeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = ChatHeaderPanelBackgroundColor
        };
        ChatTypeTabs.SetTabTitle(0, Loc.GetString("ussp-chat-ui-tab-contacts"));
        ChatTypeTabs.SetTabTitle(1, Loc.GetString("ussp-chat-ui-tab-groups"));
        WireButtons();
        ChatTypeTabs.OnTabChanged += _ => OnTabChanged();
        EmojiButton.AddStyleClass(StyleClass.ButtonOpenBoth);
        SendButton.AddStyleClass(StyleClass.ButtonOpenLeft);
        UpdateUiState();
    }

    private void WireButtons()
    {
        FindContactsButton.OnPressed += _ => OpenDiscovery?.Invoke();
        VisibleInDiscoveryCheckBox.OnToggled += args => SetVisibleInDiscovery?.Invoke(args.Pressed);
        AddContactButton.OnPressed += _ => OpenAddContact?.Invoke();
        JoinGroupButton.OnPressed += _ => JoinGroup?.Invoke();
        CreateGroupButton.OnPressed += _ => CreateGroup?.Invoke();
        MuteChatButton.OnPressed += _ => OnMutePressed?.Invoke();
        EmojiButton.OnPressed += _ => OpenEmojiPicker?.Invoke();
        SendButton.OnPressed += _ => SubmitCurrentMessage(MessageInput.Text);
        MessageInput.OnTextEntered += args => SubmitCurrentMessage(args.Text);
        EraseChatButton.OnPressed += _ => ResetActiveChat(chatId => EraseChat?.Invoke(chatId));
        LeaveChatButton.OnPressed += _ => LeaveCurrentGroup();
        CloseChatButton.OnPressed += _ => ResetActiveChat(chatId => CloseChat?.Invoke(chatId), refreshUi: true);
    }

    private void OnTabChanged()
    {
        UpdateContactsList();
    }

    public void UpdateState(USSPChatUiState state)
    {
        OwnIdLabel.Text = state.ChatId;
        Contacts = state.Contacts;
        Groups = state.Groups;
        ActiveChatId = state.ActiveChat;
        VisibleInDiscoveryCheckBox.Pressed = state.VisibleInDiscovery;
        _canSendMessages = state.CanSendMessages;

        if (state.DiscoveryList != null)
            DiscoveryListReceived?.Invoke(state.DiscoveryList);

        MuteChatButton.TexturePath = state.Muted
            ? "/Textures/_DeadSpace/Actions/arkalyse_actions.rsi/mute.png"
            : "/Textures/Structures/Wallmounts/intercom.rsi/speaker.png";
        MuteChatButton.ToolTip = state.Muted
            ? Loc.GetString("ussp-chat-ui-unmute-tooltip")
            : Loc.GetString("ussp-chat-ui-mute-tooltip");

        UpdateContactsList();
        UpdateMessages(state.ActiveChatMessages);

        UpdateUiState();
    }

    public void InitializeEmojiPicker()
    {
        _emojiPopup = new USSPChatEmojiPopup();
        _emojiPopup.OnEmojiSelected += emoji =>
        {
            if (ActiveChatId != null)
            {
                MessageInput.Text += emoji;
                MessageInput.CursorPosition = MessageInput.Text.Length;
            }
        };
    }

    public void OpenEmojiPickerInternal()
    {
        if (_emojiPopup == null)
            InitializeEmojiPicker();

        _emojiPopup?.OpenCentered();
    }

    private void UpdateContactsList()
    {
        ContactsContainer.RemoveAllChildren();
        GroupsContainer.RemoveAllChildren();

        NoContactsLabel.Visible = Contacts.Count == 0 && ChatTypeTabs.CurrentTab == 0;
        NoGroupsLabel.Visible = Groups.Count == 0 && ChatTypeTabs.CurrentTab == 1;

        if (ChatTypeTabs.CurrentTab == 0)
        {
            foreach (var contact in Contacts.Values.OrderBy(c => c.ContactName))
            {
                var control = new USSPChatContactControl(contact);
                control.OnPressed += () => SetActiveChat?.Invoke(contact.ContactId);
                ContactsContainer.AddChild(control);
            }
        }
        else
        {
            foreach (var group in Groups.Values.OrderBy(g => g.GroupName))
            {
                var control = new USSPChatGroupControl(group);
                control.OnPressed += () => SetActiveChat?.Invoke(group.GroupId);
                GroupsContainer.AddChild(control);
            }
        }
    }

    private void UpdateMessages(List<ChatMessage>? messages)
    {
        MessagesContainer.RemoveAllChildren();
        if (messages == null)
            return;

        foreach (var message in messages)
        {
            var messageControl = new USSPChatMessageControl(ResolveMessageDisplay(message));
            MessagesContainer.AddChild(messageControl);
            MessagesContainer.AddChild(new Control { MinSize = new Vector2(0, 4) });
        }
    }

    private ChatMessage ResolveMessageDisplay(ChatMessage message)
    {
        if (message.IsOwnMessage)
            return message;

        if (Contacts.TryGetValue(message.SenderId, out var contact))
        {
            return new ChatMessage(
                message.SenderId,
                contact.ContactName,
                message.Message,
                message.Timestamp,
                message.IsOwnMessage,
                message.Delivered);
        }

        return message;
    }

    private void UpdateUiState()
    {
        var hasActiveChat = HasActiveChat();
        var isGroupChat = IsActiveGroupChat();
        var canCompose = hasActiveChat && _canSendMessages;
        MessageInput.Editable = canCompose;
        MessageInput.PlaceHolder = hasActiveChat
            ? Loc.GetString(_canSendMessages ? "ussp-chat-ui-message-placeholder" : "ussp-chat-ui-readonly-input")
            : Loc.GetString("ussp-chat-ui-select-chat-input");
        EmojiButton.Disabled = !canCompose;
        SendButton.Disabled = !canCompose;
        VisibleInDiscoveryCheckBox.Visible = _canSendMessages;
        VisibleInDiscoveryCheckBox.Disabled = !_canSendMessages;
        FindContactsButton.Visible = _canSendMessages;
        AddContactButton.Visible = _canSendMessages;
        JoinGroupButton.Visible = _canSendMessages;
        CreateGroupButton.Visible = _canSendMessages;
        EraseChatButton.Visible = _canSendMessages && hasActiveChat && !isGroupChat;
        LeaveChatButton.Visible = _canSendMessages && hasActiveChat && isGroupChat;
        CloseChatButton.Visible = hasActiveChat;

        if (!hasActiveChat)
        {
            ChatTitle.Text = Loc.GetString("ussp-chat-ui-select-chat");
            MessagesContainer.RemoveAllChildren();
            return;
        }

        ChatTitle.Text = ResolveActiveChatTitle(isGroupChat);
    }

    private void SubmitCurrentMessage(string text)
    {
        if (!HasActiveChat() || string.IsNullOrWhiteSpace(text))
            return;

        SendMessage?.Invoke(text);
        MessageInput.Text = string.Empty;
    }

    private void LeaveCurrentGroup()
    {
        if (!IsActiveGroupChat())
            return;

        ResetActiveChat(chatId => LeaveChat?.Invoke(chatId), refreshUi: true);
    }

    private void ResetActiveChat(Action<string> handler, bool refreshUi = false)
    {
        if (!HasActiveChat())
            return;

        handler(ActiveChatId!);
        ActiveChatId = null;

        if (refreshUi)
            UpdateUiState();
    }

    private bool HasActiveChat()
    {
        return ActiveChatId != null;
    }

    private bool IsActiveGroupChat()
    {
        return ActiveChatId != null && Groups.ContainsKey(ActiveChatId);
    }

    private string ResolveActiveChatTitle(bool isGroupChat)
    {
        if (ActiveChatId == null)
            return Loc.GetString("ussp-chat-ui-select-chat");

        if (isGroupChat && Groups.TryGetValue(ActiveChatId, out var group))
            return $"{group.GroupName} {ActiveChatId}";

        if (!isGroupChat && Contacts.TryGetValue(ActiveChatId, out var contact))
            return contact.ContactName;

        return Loc.GetString("ussp-chat-ui-unknown-chat");
    }
}
