using Content.Shared.DeadSpace.Soyuz.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Soyuz.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class USSPChatDiscoveryPopup : DefaultWindow
{
    public Action<string, string>? OnAddContact;

    public USSPChatDiscoveryPopup()
    {
        RobustXamlLoader.Load(this);
        CancelButton.OnPressed += _ => Close();
    }

    public void SetEntries(IReadOnlyList<DiscoveryEntry> entries)
    {
        EntriesContainer.RemoveAllChildren();
        EmptyLabel.Visible = entries.Count == 0;

        foreach (var entry in entries)
        {
            EntriesContainer.AddChild(BuildEntryRow(entry));
        }
    }

    private BoxContainer BuildEntryRow(DiscoveryEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        row.AddChild(new Label
        {
            Text = $"{entry.DisplayName} ({entry.ChatId})",
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center
        });

        row.AddChild(BuildAddButton(entry));
        return row;
    }

    private Button BuildAddButton(DiscoveryEntry entry)
    {
        var button = new Button { Text = Loc.GetString("ussp-chat-ui-add") };
        button.OnPressed += _ =>
        {
            OnAddContact?.Invoke(entry.ChatId, entry.DisplayName);
            Close();
        };

        return button;
    }
}
