using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Soyuz.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class USSPChatJoinGroupPopup : DefaultWindow
{
    private const int GroupIdLength = 6;

    public Func<string, bool>? OnGroupJoined;

    public USSPChatJoinGroupPopup()
    {
        RobustXamlLoader.Load(this);
        CancelButton.OnPressed += _ => Close();
        JoinButton.OnPressed += _ => Submit();
        GroupIdInput.OnTextEntered += _ => Submit();
        GroupIdInput.OnTextChanged += _ => SetError(null);
    }

    private static string NormalizeGroupId(string groupId)
    {
        return groupId.Trim().Replace(" ", "").ToUpperInvariant();
    }

    private void Submit()
    {
        if (!TryBuildGroupId(out var groupId))
            return;

        if (OnGroupJoined?.Invoke(groupId) == false)
            return;

        Close();
    }

    private bool TryBuildGroupId(out string groupId)
    {
        groupId = string.Empty;

        if (string.IsNullOrWhiteSpace(GroupIdInput.Text))
        {
            SetError("ussp-chat-ui-group-id-invalid");
            return false;
        }

        groupId = NormalizeGroupId(GroupIdInput.Text);
        if (!IsValidGroupId(groupId))
        {
            SetError("ussp-chat-ui-group-id-invalid");
            return false;
        }

        SetError(null);
        return true;
    }

    private static bool IsValidGroupId(string value)
    {
        return value.Length == GroupIdLength
               && value.All(static c => c is >= 'A' and <= 'Z' or >= '0' and <= '9')
               && value.Any(char.IsAsciiLetter)
               && value.Any(char.IsAsciiDigit);
    }

    private void SetError(string? locKey)
    {
        ErrorLabel.Visible = !string.IsNullOrWhiteSpace(locKey);
        ErrorLabel.Text = locKey == null
            ? string.Empty
            : Loc.GetString(locKey);
    }
}
