using Content.Shared.DeadSpace.Soyuz.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;

namespace Content.Client.DeadSpace.Soyuz.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class USSPChatContactControl : Control
{
    public Action? OnPressed;

    public USSPChatContactControl(ChatContact contact)
    {
        RobustXamlLoader.Load(this);

        ContactName.Text = BuildDisplayName(contact);
        MainButton.OnPressed += _ => OnPressed?.Invoke();
    }

    private static string BuildDisplayName(ChatContact contact)
    {
        return contact.HasUnread
            ? contact.ContactName + Loc.GetString("ussp-chat-ui-unread-indicator")
            : contact.ContactName;
    }
}
