using Content.Shared.DeadSpace.Soyuz.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;

namespace Content.Client.DeadSpace.Soyuz.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class USSPChatGroupControl : Control
{
    public Action? OnPressed;

    public USSPChatGroupControl(ChatGroup group)
    {
        RobustXamlLoader.Load(this);

        GroupName.Text = BuildDisplayName(group);
        MemberCount.Text = group.MemberCount.ToString();
        MainButton.OnPressed += _ => OnPressed?.Invoke();
    }

    private static string BuildDisplayName(ChatGroup group)
    {
        return group.HasUnread
            ? group.GroupName + Loc.GetString("ussp-chat-ui-unread-indicator")
            : group.GroupName;
    }
}
