using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Soyuz.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class USSPChatCreateGroupPopup : DefaultWindow
{
    private const int MaxGroupNameLength = 16;

    public Action<string>? OnGroupCreated;

    public USSPChatCreateGroupPopup()
    {
        RobustXamlLoader.Load(this);
        CancelButton.OnPressed += _ => Close();
        CreateButton.OnPressed += _ => Submit();
        GroupNameInput.OnTextEntered += _ => Submit();
    }

    private void Submit()
    {
        if (string.IsNullOrWhiteSpace(GroupNameInput.Text))
            return;

        var groupName = Truncate(GroupNameInput.Text, MaxGroupNameLength);
        OnGroupCreated?.Invoke(groupName);
        Close();
    }

    private static string Truncate(string value, int maxLength)
    {
        return value.Length <= maxLength ? value : value[..maxLength];
    }
}
