- type: gameMapPool
  id: DefaultMapPool
  maps:
  # DS14-Soyuz-start: automatic map vote pool
  - Reach
  - CorvaxSilly
  - Saltern
  - Packed
  - Cluster
  - CorvaxPaper
  - Omega
  - Elkridge
  - Barratry
  - CorvaxPearl
  - Bagel
  - Train
  - Loop
  - Plasma
  - Gemini
  - Marathon
  - Amber
  - Meta
  - Cog
  - Core
  - Gate
  - Fland
  - Convex
  - Box
  - Origin
  - Oasis
  - CorvaxAstra
  - CorvaxAvrite
  - CorvaxDelta
  - CorvaxSpectrum
  - CorvaxGlacier
  # DS14-Soyuz-end
