- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Aspid
  - Bagel
  - Barratry
  - Box
  - Cluster #DS14-Soyuz-enabled
  - Cog
  - Convex
  - Core
  - CorvaxAstra
  - CorvaxAvrite
  - CorvaxChloris
  - CorvaxDelta
  - CorvaxGlacier
  # - CorvaxPaper # Removed by Liv
  - CorvaxSilly
  - CorvaxSpectrum
  - CorvaxGlacier
  - CorvaxPearl
  - Elkridge
  - Fland
  - Gate
  - Ishimura
  - Gemini #DS14
  - Loop #DS14-Soyuz-enabled
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Packed
  - Plasma 
  - Reach #DS14-Soyuz-enabled
  # - Exo # map prototype is commented out
  - Saltern
  - Snowball # DS14-Soyuz
  - Train
