- type: gameMapPool
  id: DefaultMapPool
  maps:
  # - DSTaipan # not mappool map
  - Amber
  - Aspid
  - Bagel
  - Barratry
  - Box
  - Cluster
  - Cog
  - Core
  - Gate
  - Fland
  - Convex
  - Box
  - Origin
  - Oasis
  - CorvaxAstra
  - CorvaxAvrite
  - CorvaxDelta
  - CorvaxSpectrum
  - Elkridge
  - Fland
  - Gate
  - Gemini
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Packed
  - Plasma
  - Reach
  # - Exo # DS14-Soyuz
  - Saltern
  - Snowball
  # - Train # Shit map
  - CorvaxPearl
  - Ishimura # Выключено до одобрения Liv
