using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NetProbeUiFragment : BoxContainer
{
    public NetProbeUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
    }

    public void UpdateState(List<ProbedNetworkDevice> devices)
    {
        ProbedDeviceContainer.RemoveAllChildren();

        //Reverse the list so the oldest entries appear at the bottom
        devices.Reverse();

        //Enable scrolling if there are more entries that can fit on the screen
        ScrollContainer.HScrollEnabled = devices.Count > 9;

        foreach (var device in devices)
        {
            AddProbedDevice(device);
        }
    }

    private void AddProbedDevice(ProbedNetworkDevice device)
    {
        // DS14-start
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(4),
            StyleClasses = { "DS14MenuListRow" },
        };
        // DS14-end

        var row = new BoxContainer();
        row.HorizontalExpand = true;
        row.Orientation = LayoutOrientation.Horizontal;
        row.Margin = new Thickness(6, 4); // DS14

        var nameLabel = new Label();
        nameLabel.Text = device.Name;
        nameLabel.HorizontalExpand = true;
        nameLabel.ClipText = true;
        nameLabel.AddStyleClass("DS14MenuProfileLabel"); // DS14
        row.AddChild(nameLabel);

        addressLabel.HorizontalExpand = true;
        addressLabel.AddStyleClass("DS14MenuProfileLabel"); // DS14
        row.AddChild(addressLabel);

        var frequencyLabel = new Label();
        frequencyLabel.Text = device.Frequency;
        frequencyLabel.HorizontalExpand = true;
        frequencyLabel.ClipText = true;
        frequencyLabel.AddStyleClass("DS14MenuProfileLabel"); // DS14
        row.AddChild(frequencyLabel);

        var networkLabel = new Label();
        networkLabel.Text = device.NetId;
        networkLabel.HorizontalExpand = true;
        networkLabel.ClipText = true;
        networkLabel.AddStyleClass("DS14MenuProfileLabel"); // DS14
        row.AddChild(networkLabel);

        // DS14-start
        panel.AddChild(row);
        ProbedDeviceContainer.AddChild(panel);
        // DS14-end
    }
}
