using System.Numerics; // DS14
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface; // DS14
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC; // DS14
using Robust.Shared.Maths; // DS14

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NotekeeperUiFragment : BoxContainer
{

    public event Action<string>? OnNoteAdded;
    public event Action<string>? OnNoteRemoved;

    public NotekeeperUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        Input.OnTextEntered += _ =>
        {
            AddNote(Input.Text);
            OnNoteAdded?.Invoke(Input.Text);
            Input.Clear();
        };

        UpdateState(new List<string>());
    }

    public void UpdateState(List<string> notes)
    {
        MessageContainer.RemoveAllChildren();

        foreach (var note in notes)
        {
           AddNote(note);
        }
    }

    private void AddNote(string note)
    {
        // DS14-start
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(4),
            StyleClasses = { "DS14MenuListRow" },
        };
        // DS14-end

        var row = new BoxContainer();
        row.HorizontalExpand = true;
        row.Orientation = LayoutOrientation.Horizontal;

        var label = new Label();
        label.Text = note;
        label.HorizontalExpand = true;
        label.ClipText = true;
        // DS14-Start
		label.MinSize = new Vector2(0, 32);
        label.VerticalExpand = true;

        var copyButton = new TextureButton();
        copyButton.TexturePath = "/Textures/_DeadSpace/Interface/Notes/copy.png";
        copyButton.ModulateSelfOverride = Color.FromHex("#4a9eff");
        copyButton.OnPressed += _ =>
        {
            var clipboard = IoCManager.Resolve<IClipboardManager>();
            clipboard.SetText(note);
            copyButton.ModulateSelfOverride = Color.FromHex("#6aff6a");
        };
		// DS14-End

        var removeButton = new TextureButton();
        removeButton.AddStyleClass("windowCloseButton");
        removeButton.OnPressed += _ => OnNoteRemoved?.Invoke(note); // DS14

        row.AddChild(label);
        row.AddChild(copyButton); // DS14
        row.AddChild(removeButton);

        // DS14-start
        panel.AddChild(row);
        MessageContainer.AddChild(panel);
        // DS14-end
    }
}
