// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.DeadSpace.ERT;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class ERTCallWindow : DefaultWindow
    {
        [Dependency] private readonly IEntityManager _entMan = default!;
        private ErtResponceSystem? _ertSystem;

        public ERTCallWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _ertSystem = _entMan.System<ErtResponceSystem>();

            DeleteErtButton.OnPressed += _ => Delete();
            RefreshButton.OnPressed += _ => Refresh();
            SetArrivalButton.OnPressed += _ => SetArrival();
            SetCooldownButton.OnPressed += _ => SetCooldown();
            SetPointsButton.OnPressed += _ => SetPoints();
            ExpectedList.OnItemSelected += OnListSelected;

            if (_ertSystem != null)
                _ertSystem.OnStateUpdated += PopulateFromSystem;

            // initial request
            _ertSystem?.RequestAdminState();
        }

        private string? _selectedProtoId;

        private void OnListSelected(ItemList.ItemListSelectedEventArgs args)
        {
            if (args.ItemIndex < 0) return;
            _selectedProtoId = ExpectedList[args.ItemIndex].Metadata as string;
        }

        private void Refresh()
        {
            _ertSystem?.RequestAdminState();
        }

        private void PopulateFromSystem()
        {
            var state = _ertSystem?.LastState;
            if (state == null) return;

            ExpectedList.Clear();

            foreach (var e in state.Entries)
            {
                ExpectedList.AddItem($"{e.Name} — {e.SecondsRemaining}s ({e.Price})", metadata: e.ProtoId);
            }

            PointsEdit.Text = state.Points.ToString();
            CooldownSeconds.Text = state.CooldownSeconds.ToString();
        }

        private void SetArrival()
        {
            if (_selectedProtoId == null) return;

            if (!int.TryParse(ArrivalSeconds.Text, out var seconds))
                return;

            _ertSystem?.AdminModifyEntry(_selectedProtoId, seconds);
            Refresh();
        }

        private void Delete()
        {
            if (_selectedProtoId == null) return;
            _ertSystem?.AdminDeleteErt(_selectedProtoId);
            Refresh();
        }

        private void SetCooldown()
        {
            if (!int.TryParse(CooldownSeconds.Text, out var seconds))
                return;

            _ertSystem?.AdminSetCooldown(seconds);
            Refresh();
        }

        private void SetPoints()
        {
            if (!int.TryParse(PointsEdit.Text, out var pts))
                return;

            _ertSystem?.AdminSetPoints(pts);
            Refresh();
        }
    }
}
