# Chaplain
- type: job
  id: ERTChaplain
  name: job-name-ertchaplain
  description: job-description-ertchaplain
  playTimeTracker: JobERTChaplain
  setPreference: false
  startingGear: ERTChaplainGear
  icon: "JobIconERTChaplain" # DS14
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
    - type: MindCaptureDefence #DS14
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

# DS14-start
- type: startingGear
  id: ERTChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudAdvanced
    neck: ClothingNeckStoleChaplain
    ears: ClothingHeadsetCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    suitstorage: HolyCrossbow
    shoes: ADTClothingShoesBootsMagERT
    id: ERTChaplainIDCard
    belt: RadianceSheathFilled
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: Bible
  storage:
    back:
    - WeaponDisabler
    - CrowbarRed
    - EmergencyMedipen
    - BoxMRE
    - CrayonWhite
    - Candle
    - Candle
    - Candle
    - DrinkWaterBottleFull
    - DrinkWaterBottleFull
    - PresentQuiver
    - PresentQuiver
    - PresentQuiver
    - PresentQuiver
    - PresentQuiver
    - Censer
    belt: []
# DS14-end
