// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Shared.DeadSpace.RedPhone;
using Content.Shared.Telephone;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.RedPhone;

[GenerateTypedNameReferences]
public sealed partial class RedPhoneWindow : DefaultWindow
{
    private RedPhoneBoundUiState? _lastState;

    public event Action<NetEntity>? StartCall;
    public event Action? EndCall;

    public RedPhoneWindow()
    {
        RobustXamlLoader.Load(this);

        ContactsList.OnItemSelected += _ => UpdateButtons();
        ContactsList.OnItemDeselected += _ => UpdateButtons();

        CallButton.OnPressed += _ =>
        {
            var selected = GetSelectedPhone();
            if (selected != null)
                StartCall?.Invoke(selected.Value);
        };

        EndCallButton.OnPressed += _ => EndCall?.Invoke();
    }

    public void UpdateState(RedPhoneBoundUiState state)
    {
        _lastState = state;

        var preferredPhone = state.ActivePhone ?? GetSelectedPhone();

        ContactsList.Clear();

        foreach (var contact in state.Contacts)
        {
            var item = ContactsList.AddItem(contact.Label, metadata: contact.Phone);
            item.Disabled = !contact.Available;

            if (preferredPhone != null && preferredPhone.Value == contact.Phone)
                item.Selected = true;
        }

        var hasSelection = false;
        foreach (var _ in ContactsList.GetSelected())
        {
            hasSelection = true;
            break;
        }

        if (!hasSelection && ContactsList.Count > 0)
            ContactsList[0].Selected = true;

        EmptyLabel.Visible = state.Contacts.Count == 0;
        StatusLabel.Text = Loc.GetString(state.State switch
        {
            TelephoneState.Idle => "red-phone-status-idle",
            TelephoneState.Calling => "red-phone-status-calling",
            TelephoneState.Ringing => "red-phone-status-ringing",
            TelephoneState.InCall => "red-phone-status-in-call",
            TelephoneState.EndingCall => "red-phone-status-ending",
            _ => "red-phone-status-idle"
        });

        UpdateButtons();
    }

    private void UpdateButtons()
    {
        var state = _lastState;
        var selected = GetSelectedPhone();

        var canCall = state != null &&
                      state.State == TelephoneState.Idle &&
                      selected != null &&
                      IsAvailable(selected.Value);
        var canEnd = state != null && state.State != TelephoneState.Idle;

        CallButton.Disabled = !canCall;
        EndCallButton.Disabled = !canEnd;
    }

    private NetEntity? GetSelectedPhone()
    {
        foreach (var item in ContactsList.GetSelected())
        {
            if (item.Metadata is NetEntity phone)
                return phone;
        }

        return null;
    }

    private bool IsAvailable(NetEntity phone)
    {
        var state = _lastState;
        if (state == null)
            return false;

        foreach (var contact in state.Contacts)
        {
            if (contact.Phone == phone)
                return contact.Available;
        }

        return false;
    }
}
