// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Shared.DeadSpace.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AutoMapVoteConfigWindow : DefaultWindow
{
    public AutoMapVoteConfigWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(AutoMapVoteAdminState? state)
    {
        ConfigControl.UpdateState(state);
    }
}
