using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.LawBoardConfigurator;
using Content.Shared.FixedPoint;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.LawBoardConfigurator;

[GenerateTypedNameReferences]
public sealed partial class LawBoardConfiguratorWindow : FancyWindow
{
    private List<SiliconLaw> _laws = new();
    private bool _boardPresent;

    public event Action? OnEjectPressed;
    public event Action? OnSavePressed;

    public LawBoardConfiguratorWindow()
    {
        RobustXamlLoader.Load(this);
        NewLawButton.OnPressed += _ => AddNewLaw();
        EjectBoardButton.OnPressed += _ => OnEjectPressed?.Invoke();
        SaveButton.OnPressed += _ => OnSavePressed?.Invoke();

        BoardNameInput.PlaceHolder = Loc.GetString("law-board-configurator-ui-board-name-placeholder");
        BoardNameInput.IsValid = s => s.Length <= LawBoardConfiguratorLimits.BoardNameMaxLength;
        BoardNameInput.OnTextChanged += _ => EnforceBoardNameLimit();
        SetBoardPresent(false);
    }

    public void SetLaws(List<SiliconLaw> laws)
    {
        _laws = laws;
        LawContainer.RemoveAllChildren();

        if (!_boardPresent)
        {
            NewLawButton.Disabled = true;
            return;
        }

        NewLawButton.Disabled = _laws.Count >= LawBoardConfiguratorLimits.LawCountMax;

        foreach (var law in laws.OrderBy(l => l.Order))
        {
            var row = new LawBoardConfiguratorLawRow();
            row.SetLaw(law);
            row.MoveLawUp += MoveLawUp;
            row.MoveLawDown += MoveLawDown;
            row.DeleteAction += DeleteLaw;
            LawContainer.AddChild(row);
        }

        LawContainer.InvalidateMeasure();
        LawContainer.InvalidateArrange();
    }

    public List<SiliconLaw> GetLaws()
    {
        return _laws;
    }

    public void SetBoardName(string boardName)
    {
        BoardNameInput.Text = boardName;
        EnforceBoardNameLimit();
    }

    public void SetBoardPresent(bool present)
    {
        _boardPresent = present;
        NoBoardPanel.Visible = !present;
        BoardEditorContainer.Visible = present;
        EjectBoardButton.Disabled = !present;
        SaveButton.Disabled = !present;
        NewLawButton.Disabled = !present || _laws.Count >= LawBoardConfiguratorLimits.LawCountMax;
        BoardNameInput.Editable = present;
    }

    public string GetBoardName()
    {
        return BoardNameInput.Text.Trim();
    }

    private void AddNewLaw()
    {
        if (_laws.Count >= LawBoardConfiguratorLimits.LawCountMax)
            return;

        var newLaw = new SiliconLaw
        {
            Order = FixedPoint2.New(_laws.Count + 1),
        };

        _laws.Add(newLaw);
        SetLaws(_laws);
    }

    private void DeleteLaw(SiliconLaw law)
    {
        _laws.Remove(law);
        SetLaws(_laws);
    }

    private void MoveLawDown(SiliconLaw law)
    {
        if (_laws.Count == 0)
            return;

        var index = _laws.IndexOf(law);
        if (index == -1)
            return;

        _laws[index].Order += FixedPoint2.New(1);
        SetLaws(_laws);
    }

    private void MoveLawUp(SiliconLaw law)
    {
        if (_laws.Count == 0)
            return;

        var index = _laws.IndexOf(law);
        if (index == -1)
            return;

        _laws[index].Order += FixedPoint2.New(-1);
        SetLaws(_laws);
    }

    private void EnforceBoardNameLimit()
    {
        if (BoardNameInput.Text.Length <= LawBoardConfiguratorLimits.BoardNameMaxLength)
            return;

        BoardNameInput.Text = BoardNameInput.Text[..LawBoardConfiguratorLimits.BoardNameMaxLength];
        BoardNameInput.CursorPosition = BoardNameInput.Text.Length;
    }
}
