using Content.Shared.DeadSpace.LawBoardConfigurator;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.LawBoardConfigurator;

[GenerateTypedNameReferences]
public sealed partial class LawBoardConfiguratorLawRow : BoxContainer
{
    public event Action<SiliconLaw>? MoveLawUp;
    public event Action<SiliconLaw>? MoveLawDown;
    public event Action<SiliconLaw>? DeleteAction;

    private SiliconLaw? _law;

    public LawBoardConfiguratorLawRow()
    {
        RobustXamlLoader.Load(this);

        MoveUp.OnPressed += _ =>
        {
            if (_law != null)
                MoveLawUp?.Invoke(_law);
        };
        MoveDown.OnPressed += _ =>
        {
            if (_law != null)
                MoveLawDown?.Invoke(_law);
        };
        Delete.OnPressed += _ =>
        {
            if (_law != null)
                DeleteAction?.Invoke(_law);
        };

        LawContent.OnTextChanged += _ => OnLawTextChanged();
        LawContent.Placeholder = new Rope.Leaf(Loc.GetString("silicon-law-ui-placeholder"));
    }

    public void SetLaw(SiliconLaw law)
    {
        _law = law;

        var lawText = Loc.TryGetString(law.LawString, out var localized)
            ? localized
            : law.LawString;
        if (lawText.Length > LawBoardConfiguratorLimits.LawTextMaxLength)
            lawText = lawText[..LawBoardConfiguratorLimits.LawTextMaxLength];

        LawContent.TextRope = new Rope.Leaf(lawText);
        PositionText.Text = law.Order.ToString();
    }

    private void OnLawTextChanged()
    {
        var lawText = Rope.Collapse(LawContent.TextRope);
        if (lawText.Length > LawBoardConfiguratorLimits.LawTextMaxLength)
        {
            lawText = lawText[..LawBoardConfiguratorLimits.LawTextMaxLength];
            LawContent.TextRope = new Rope.Leaf(lawText);
            LawContent.CursorPosition = new TextEdit.CursorPos(lawText.Length, TextEdit.LineBreakBias.Bottom);
        }

        if (_law != null)
            _law.LawString = lawText.Trim();
    }
}
