using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared.Audio.Jukebox;
using Content.Shared.DeadSpace.Ports.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Audio.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class JukeboxMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private AudioSystem _audioSystem;
    // DS-14
    private JukeboxSystem _jukeboxSystem;
    // DS-14 start
    private readonly List<JukeboxPrototype> _allSongs = new();

    /// <summary>
    /// Are we currently 'playing' or paused for the play / pause button.
    /// </summary>
    private bool _playState;
    private bool _updatingSongList;
    private ProtoId<JukeboxPrototype>? _selectedSongId;

    /// <summary>
    /// True if playing, false if paused.
    /// </summary>
    public event Action<bool>? OnPlayPressed;
    public event Action? OnNextPressed;
    public event Action? OnPreviousPressed;
    public event Action<bool>? OnShuffleToggled;
    public event Action<bool>? OnRepeatToggled;
    public event Action<ProtoId<JukeboxPrototype>>? OnSongSelected;
    public event Action<float>? SetTime;
    public event Action<float>? SetVolume;

    // DS-14
    private EntityUid _jukebox;
    private EntityUid? _audio;

    private float _lockTimer;
    private float _volume = JukeboxVolume.DefaultValue;
    private float _lastSentVolume = JukeboxVolume.DefaultValue;
    private float _volumeSendAccumulator;
    private float _volumeInteractionTimer;
    private bool _pendingVolumeSend;
    // DS-14
    private bool _awaitingVolumeSync;
    private bool _updatingVolume;
    private const float VolumeSendInterval = 0.12f;
    private const float VolumeSendTolerance = 0.01f;
    // DS-14
    private const float VolumeInteractionHoldTime = 0.2f;
    // DS-14
    private const string PlayIconTexturePath = "/Textures/Interface/AdminActions/play.png";
    // DS-14
    private const string PauseIconTexturePath = "/Textures/Interface/AdminActions/pause.png";
    // DS-14 end

    public JukeboxMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();
        // DS-14
        _jukeboxSystem = _entManager.System<JukeboxSystem>();
        // DS-14 start
        VolumeSlider.MinValue = JukeboxVolume.MinValue;
        VolumeSlider.MaxValue = JukeboxVolume.MaxValue;
        VolumeSlider.Page = 0f;

        MusicList.OnItemSelected += args =>
        {
            if (_updatingSongList)
                return;

            var entry = MusicList[args.ItemIndex];

            if (entry.Metadata is not string juke)
                return;

            OnSongSelected?.Invoke(juke);
        };

        PlayButton.OnPressed += args =>
        {
            OnPlayPressed?.Invoke(!_playState);
        };

        PreviousButton.OnPressed += _ => OnPreviousPressed?.Invoke();
        NextButton.OnPressed += _ => OnNextPressed?.Invoke();
        ShuffleButton.OnToggled += args => OnShuffleToggled?.Invoke(args.Pressed);
        RepeatButton.OnToggled += args => OnRepeatToggled?.Invoke(args.Pressed);
        SearchInput.OnTextChanged += _ => RefreshSongList();
        PlaybackSlider.OnReleased += PlaybackSliderKeyUp;
        VolumeSlider.OnValueChanged += _ => OnVolumeSliderChanged();
        // DS-14 end

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio), force: true);
        SetVolumeSlider(_volume, force: true);
    }

    public void SetJukebox(EntityUid jukebox)
    {
        _jukebox = jukebox;

        // DS-14 start
        if (!_jukeboxSystem.TryGetVolumeOverride(jukebox, out var volume))
            return;

        _awaitingVolumeSync = true;
        SetVolumeSlider(volume, force: true);
        // DS-14 end
    }

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
        // DS-14 start
        if (HasActiveLocalVolumeOverride)
            TryApplyLocalVolume(_volume);
        // DS-14 end
    }

    private void PlaybackSliderKeyUp(Slider args)
    {
        SetTime?.Invoke(PlaybackSlider.Value);
        _lockTimer = 0.5f;
    }

    /// <summary>
    /// Re-populates the list of jukebox prototypes available.
    /// </summary>
    public void Populate(IEnumerable<JukeboxPrototype> jukeboxProtos)
    {
        // DS-14 start
        _allSongs.Clear();
        _allSongs.AddRange(jukeboxProtos);
        _allSongs.Sort(static (left, right) => string.Compare(left.Name, right.Name, StringComparison.OrdinalIgnoreCase));
        // DS-14 end
        RefreshSongList();
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;

        // DS-14 start
        if (playing)
        {
            PlayIcon.TexturePath = PauseIconTexturePath;
            PlayButton.ToolTip = Loc.GetString("jukebox-menu-buttonpause");
            return;
        }

        PlayIcon.TexturePath = PlayIconTexturePath;
        PlayButton.ToolTip = Loc.GetString("jukebox-menu-buttonplay");
        // DS-14 end
    }

    public void SetSelectedSong(ProtoId<JukeboxPrototype>? songId, string? name, float length)
    {
        var resetSlider = _selectedSongId != songId || Math.Abs(PlaybackSlider.MaxValue - length) > 0.05f;
        _selectedSongId = songId;
        SetSelectedSongText(name);
        PlaybackSlider.MaxValue = length;

        if (resetSlider)
            PlaybackSlider.SetValueWithoutEvent(0);

        RefreshSelection();
    }

    public void SetShuffleEnabled(bool enabled)
    {
        ShuffleButton.SetClickPressed(enabled);
    }

    public void SetRepeatEnabled(bool enabled)
    {
        RepeatButton.SetClickPressed(enabled);
    }

    public void SetVolumeSlider(float volume, bool force = false)
    {
        volume = JukeboxVolume.Clamp(volume);

        // DS-14 start
        if (!force && HasActiveLocalVolumeOverride)
        {
            if (_awaitingVolumeSync && Math.Abs(_volume - volume) <= VolumeSendTolerance)
