// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.DeadSpace.ERT;

namespace Content.Client.DeadSpace.ERT.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ErtComputerShuttleWindow : DefaultWindow
    {
        private ErtComputerShuttleBoundUserInterfaceState? _lastUpdate;
        public ErtComputerShuttleWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
        }

        public void Populate(ErtComputerShuttleBoundUserInterfaceState state)
        {
            _lastUpdate = state;
        }

    }
}