// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.StationAI.UI;

[GenerateTypedNameReferences]
public sealed partial class StationAiLeaveRoundConfirmationWindow : FancyWindow
{
    public event Action? Confirmed;

    public StationAiLeaveRoundConfirmationWindow()
    {
        RobustXamlLoader.Load(this);

        WarningTitle.Text = Loc.GetString("station-ai-leave-round-confirmation-warning-title");
        WarningBody.SetMessage(Loc.GetString("station-ai-leave-round-confirmation-warning-body"));
        CancelButton.OnPressed += _ => Close();
        ConfirmButton.OnPressed += _ => Confirmed?.Invoke();
    }
}
