using Content.Client.Administration.Managers;
using Content.Client.DeadSpace.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.ObjectsTab;

[GenerateTypedNameReferences]
public sealed partial class ObjectsTabEntry : PanelContainer
{
    public NetEntity AssocEntity;

    public Action<NetEntity>? OnTeleport;
    public Action<NetEntity>? OnDelete;

    public ObjectsTabEntry(IClientAdminManager manager, string name, NetEntity nent) // DS14
    {
        RobustXamlLoader.Load(this);

        AssocEntity = nent;
        EIDLabel.Text = nent.ToString();
        NameLabel.Text = name;
        // DS14-start
        AddProfileLabelStyle(NameLabel, EIDLabel);
        AddProfileButtonStyle(TeleportButton, DeleteButton);
        // DS14-end

        TeleportButton.Disabled = !manager.CanCommand("tpto");
        DeleteButton.Disabled = !manager.CanCommand("delete");

        TeleportButton.OnPressed += _ => OnTeleport?.Invoke(nent);
        DeleteButton.OnPressed += _ => OnDelete?.Invoke(nent);
    }

    // DS14-start
    private static void AddProfileLabelStyle(params Label[] labels)
    {
        foreach (var label in labels)
        {
            if (!label.StyleClasses.Contains(DeadSpaceMenuSheetlet.ProfileLabel))
                label.AddStyleClass(DeadSpaceMenuSheetlet.ProfileLabel);
        }
    }

    private static void AddProfileButtonStyle(params Button[] buttons)
    {
        foreach (var button in buttons)
        {
            if (!button.StyleClasses.Contains(DeadSpaceMenuSheetlet.ProfileControl))
                button.AddStyleClass(DeadSpaceMenuSheetlet.ProfileControl);

            button.TextAlign = Label.AlignMode.Center;
        }
    }
    // DS14-end
}
