- type: cargoProduct
  id: SoyuzFlashAutoRechargeCargo
  icon:
    sprite: _DeadSpace/_Soyuz/Objects/Weapons/Melee/flash.rsi
    state: flash
  product: SoyuzBlueprintFlash
  cost: 10000
  category: cargoproduct-category-name-security
  group: security

- type: cargoProduct
  id: SoyuzStunbatonCargo
  icon:
    sprite: _DeadSpace/_Soyuz/Objects/Weapons/Melee/stunbaton.rsi
    state: stunbaton_off
  product: SoyuzBlueprintStunbaton
  cost: 10000
  category: cargoproduct-category-name-security
  group: security

- type: cargoProduct
  id: SoyuzWeaponDisablerCargo
  icon:
    sprite: _DeadSpace/_Soyuz/Objects/Weapons/Guns/taser.rsi
    state: taser
  product: SoyuzBlueprintDisabler
  cost: 10000
  category: cargoproduct-category-name-security
  group: security

- type: cargoProduct
  id: CrateSecurityBlueprintsTier2Cargo
  icon:
    sprite: Objects/Tools/blueprint.rsi
    state: icon
  product: CrateSecurityBlueprintsTier2
  cost: 29500
  category: cargoproduct-category-name-security
  group: security