// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.Objectives.Controls;
using Content.Shared.DeadSpace.Skills;
using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.Skill;

[GenerateTypedNameReferences]
public sealed partial class SkillsListWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private static readonly StyleBoxFlat ClickableSkillCardStyle = new()
    {
        BackgroundColor = Color.FromHex("#25252A"),
        BorderColor = Color.FromHex("#3B3E56"),
        BorderThickness = new Thickness(1)
    };

    public event Action<string>? SkillPressed;

    public bool ShowsForeignSkills { get; private set; }

    public SkillsListWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void SetSkills(List<SkillInfo> skills, string? targetName = null)
    {
        SkillsContainer.RemoveAllChildren();

        if (targetName != null)
        {
            TargetNameLabel.Text = targetName;
            TargetNameLabel.Visible = true;
            ShowsForeignSkills = true;
        }
        else
        {
            TargetNameLabel.Visible = false;
            ShowsForeignSkills = false;
        }

        if (skills.Count == 0)
        {
            var noSkillsLabel = new Label
            {
                Text = Loc.GetString("skills-list-no-skills"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 20, 0, 0)
            };
            SkillsContainer.AddChild(noSkillsLabel);
            return;
        }

        var spriteSystem = _entManager.System<SpriteSystem>();

        foreach (var skill in skills)
        {
            var innerContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(8, 6, 8, 6),
                HorizontalExpand = true
            };

            var conditionControl = new ObjectiveConditionsControl
            {
                HorizontalExpand = true
            };
            // Use icon size from skill prototype
            var iconSize = new Vector2(skill.IconSize, skill.IconSize);
            conditionControl.ProgressTexture.MinSize = iconSize;
            conditionControl.ProgressTexture.SetSize = iconSize;
            conditionControl.ProgressTexture.Stretch = TextureRect.StretchMode.Scale;
            conditionControl.ProgressTexture.Texture = spriteSystem.Frame0(skill.Icon);
            conditionControl.ProgressTexture.Progress = skill.Progress;

            var titleMessage = new FormattedMessage();
            var descriptionMessage = new FormattedMessage();

            if (skill.HighlightAsUnknown)
                titleMessage.PushColor(Color.LimeGreen);

            titleMessage.AddText(skill.Name);
            descriptionMessage.AddText(skill.Description);

            conditionControl.Title.SetMessage(titleMessage);
            conditionControl.Description.SetMessage(descriptionMessage);

            // Progress percentage label
            var progressLabel = new Label
            {
                Text = $"{(int)(skill.Progress * 100)}%",
                StyleClasses = { StyleNano.StyleClassLabelSubText },
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Right,
                Margin = new Thickness(10, 0, 5, 0),
                MinWidth = 40
            };

            innerContainer.AddChild(conditionControl);
            innerContainer.AddChild(progressLabel);

            Control card = new PanelContainer
            {
                StyleClasses = { StyleNano.StyleClassTooltipPanel },
                HorizontalExpand = true
            };

            if (skill.CanLearnFromSource)
            {
                var button = new ContainerButton
                {
                    HorizontalExpand = true,
                    StyleBoxOverride = ClickableSkillCardStyle
                };
                button.AddChild(innerContainer);
                button.OnPressed += _ => SkillPressed?.Invoke(skill.PrototypeId);
                card = button;
            }
            else
            {
                ((PanelContainer) card).AddChild(innerContainer);
            }

            SkillsContainer.AddChild(card);
        }
    }
}
