using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.Soyuz.RuneBook;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Soyuz.RuneBook;

[GenerateTypedNameReferences]
public sealed partial class RuneBookWindow : FancyWindow
{
    private enum LayoutMode : byte
    {
        Wide,
        Compact,
        Narrow
    }

    private static readonly Vector2 PreferredOpenSize = new(1648, 900);
    private static readonly Vector2 WindowMargin = new(48, 92);
    private static readonly Color PageDark = Color.FromHex("#6b4a2e");
    private static readonly Color BlueMagic = Color.FromHex("#6fc7ff");
    private static readonly Color RedMagic = Color.FromHex("#b53a36");
    private static readonly Color ActiveTab = Color.FromHex("#9a7442");
    private static readonly Color InactiveTab = Color.FromHex("#5b4532");

    private RuneBookBoundUserInterfaceState? _state;
    private int _selectedRune = -1;
    private LayoutMode? _layoutMode;

    public event Action<int>? OnPageSelected;
    public event Action<int, RuneBookSegment[]>? OnCheckRune;
    public event Action<int>? OnRipPage;

    public RuneBookWindow()
    {
        RobustXamlLoader.Load(this);

        PreviousHeaderButton.OnPressed += _ => SelectPageOffset(-1);
        PreviousBottomButton.OnPressed += _ => SelectPageOffset(-1);
        NextHeaderButton.OnPressed += _ => SelectPageOffset(1);
        NextBottomButton.OnPressed += _ => SelectPageOffset(1);

        DrawingControl.OnSegmentsChanged += UpdateActionButtons;

        UndoButton.OnPressed += _ =>
        {
            DrawingControl.Undo();
            UpdateActionButtons();
        };

        ClearButton.OnPressed += _ =>
        {
            DrawingControl.Clear();
            UpdateActionButtons();
        };

        CheckButton.OnPressed += _ =>
        {
            if (_selectedRune >= 0)
                OnCheckRune?.Invoke(_selectedRune, DrawingControl.GetSegments());
        };

        RipButton.OnPressed += _ =>
        {
            if (_state != null)
                OnRipPage?.Invoke(_state.CurrentPage);
        };

        AllRunesTab.OnPressed += _ => SelectSection(AllRunesTab);
        VerifiedTab.OnPressed += _ => SelectSection(VerifiedTab);
        NotesTab.OnPressed += _ => SelectSection(NotesTab);

        ToolLineButton.Pressed = true;
        ToolLineButton.OnPressed += _ => ToolLineButton.Pressed = true;

        CheckButton.ModulateSelfOverride = Color.FromHex("#2d5f93");
        RipButton.ModulateSelfOverride = RedMagic;

        SelectSection(AllRunesTab);
    }

    protected override void Opened()
    {
        base.Opened();

        ApplyPreferredOpenSize();
        ApplyAdaptiveLayout();
        RecenterWindow(new Vector2(0.5f, 0.48f));
    }

    protected override void Resized()
    {
        base.Resized();
        ApplyAdaptiveLayout();
    }

    public void UpdateState(RuneBookBoundUserInterfaceState state)
    {
        _state = state;
        var pageRunes = RuneBookRuneLibrary.GetRunesForPage(state.CurrentPage);

        if (!pageRunes.Contains(_selectedRune))
        {
            _selectedRune = pageRunes.Length > 0 ? pageRunes[0] : -1;
            DrawingControl.Clear();
        }

        PageLabel.Text = Loc.GetString("rune-book-ui-page",
            ("page", state.CurrentPage + 1),
            ("pages", state.PageCount));

        FieldTitleLabel.Text = Loc.GetString("rune-book-ui-field-title",
            ("size", RuneBookRuneLibrary.GridSize));

        RuneTitle.Text = Loc.GetString("rune-book-ui-runes-on-page-count",
            ("count", pageRunes.Length),
            ("total", state.RuneCount));

        SelectedRuneNameLabel.Text = _selectedRune >= 0
            ? Loc.GetString("rune-book-ui-selected-rune", ("rune", _selectedRune + 1))
            : Loc.GetString("rune-book-ui-selected-rune-unknown");

        SelectedRuneDescriptionLabel.Text = Loc.GetString("rune-book-ui-selected-rune-desc");

        DrawingControl.TargetRune = _selectedRune;
        DrawingControl.PageRipped = IsPageRipped(state.CurrentPage);
        RunePreview.RuneId = _selectedRune;

        RebuildRuneCards(pageRunes);
        UpdateResult(state);
        UpdateActionButtons();
    }

    private void RebuildRuneCards(int[] pageRunes)
    {
        RuneGrid.RemoveAllChildren();
        RuneGrid.Columns = Math.Max(pageRunes.Length, 1);

        var pageRipped = _state != null && IsPageRipped(_state.CurrentPage);
        foreach (var runeId in pageRunes)
        {
            var card = new RuneBookRuneCard(runeId)
            {
                Selected = runeId == _selectedRune,
                Disabled = pageRipped,
                MinSize = new Vector2(92, 76)
            };

            card.OnSelected += SelectRune;
            RuneGrid.AddChild(card);
        }
    }

    private void SelectRune(int runeId)
    {
        if (_state != null && IsPageRipped(_state.CurrentPage))
            return;

        _selectedRune = runeId;
        DrawingControl.TargetRune = runeId;
        RunePreview.RuneId = runeId;
        DrawingControl.Clear();

        if (_state != null)
            RebuildRuneCards(RuneBookRuneLibrary.GetRunesForPage(_state.CurrentPage));

        UpdateActionButtons();
    }

    private void SelectPageOffset(int offset)
    {
        if (_state == null)
            return;

        var page = Math.Clamp(_state.CurrentPage + offset, 0, Math.Max(_state.PageCount - 1, 0));
        OnPageSelected?.Invoke(page);
    }

    private void UpdateResult(RuneBookBoundUserInterfaceState state)
    {
        switch (state.LastResult)
        {
            case RuneBookCheckResult.Success:
                ResultLabel.Text = Loc.GetString("rune-book-ui-result-success");
                ResultLabel.FontColorOverride = BlueMagic;
                StatusLabel.Text = Loc.GetString("rune-book-ui-result-success-details",
                    ("score", state.LastScore));
                break;
            case RuneBookCheckResult.Failure:
                ResultLabel.Text = Loc.GetString("rune-book-ui-result-failure");
                ResultLabel.FontColorOverride = RedMagic;
                StatusLabel.Text = Loc.GetString("rune-book-ui-result-failure-details",
                    ("score", state.LastScore),
                    ("missing", state.LastMissingSegments),
                    ("extra", state.LastExtraSegments));
                break;
            case RuneBookCheckResult.PageRipped:
                ResultLabel.Text = Loc.GetString("rune-book-ui-result-ripped");
                ResultLabel.FontColorOverride = RedMagic;
                StatusLabel.Text = Loc.GetString("rune-book-ui-result-ripped-details");
                break;
            case RuneBookCheckResult.InvalidRune:
                ResultLabel.Text = Loc.GetString("rune-book-ui-result-invalid");
                ResultLabel.FontColorOverride = RedMagic;
                StatusLabel.Text = Loc.GetString("rune-book-ui-result-invalid-details");
                break;
            default:
                ResultLabel.Text = Loc.GetString("rune-book-ui-result-none");
                ResultLabel.FontColorOverride = PageDark;
                StatusLabel.Text = Loc.GetString("rune-book-ui-result-none-details");
                break;
        }
    }

    private void UpdateActionButtons()
    {
        if (_state == null)
            return;

        var pageRipped = IsPageRipped(_state.CurrentPage);
        PreviousHeaderButton.Disabled = _state.CurrentPage <= 0;
        PreviousBottomButton.Disabled = _state.CurrentPage <= 0;
        NextHeaderButton.Disabled = _state.CurrentPage >= _state.PageCount - 1;
        NextBottomButton.Disabled = _state.CurrentPage >= _state.PageCount - 1;
        UndoButton.Disabled = !DrawingControl.HasSegments || pageRipped;
        ClearButton.Disabled = !DrawingControl.HasSegments || pageRipped;
        CheckButton.Disabled = _selectedRune < 0 || !DrawingControl.HasSegments || pageRipped;
        RipButton.Disabled = pageRipped;
    }

    private void SelectSection(Button active)
    {
        AllRunesTab.ModulateSelfOverride = active == AllRunesTab ? ActiveTab : InactiveTab;
        VerifiedTab.ModulateSelfOverride = active == VerifiedTab ? ActiveTab : InactiveTab;
        NotesTab.ModulateSelfOverride = active == NotesTab ? ActiveTab : InactiveTab;
        LockedTab.ModulateSelfOverride = InactiveTab;
    }

    private void ApplyPreferredOpenSize()
    {
        if (Parent == null)
            return;

        var available = Vector2.Max(Parent.Size - WindowMargin, MinSize);
        SetSize = Vector2.Max(Vector2.Min(PreferredOpenSize, available), MinSize);
    }

    private void ApplyAdaptiveLayout()
    {
        var width = float.IsNaN(SetSize.X) ? Size.X : SetSize.X;
        var mode = width switch
        {
            >= 1400 => LayoutMode.Wide,
            >= 1040 => LayoutMode.Compact,
            _ => LayoutMode.Narrow
        };

        if (_layoutMode == mode)
            return;

        _layoutMode = mode;

        var wide = mode == LayoutMode.Wide;
        var narrow = mode == LayoutMode.Narrow;

        MainLayout.Orientation = narrow
            ? BoxContainer.LayoutOrientation.Vertical
            : BoxContainer.LayoutOrientation.Horizontal;
        SectionTabs.Orientation = narrow
            ? BoxContainer.LayoutOrientation.Horizontal
            : BoxContainer.LayoutOrientation.Vertical;
        SectionTabs.Visible = wide || narrow;
        SectionTabs.MinWidth = wide ? 96 : 0;
        SectionTabs.Margin = narrow
            ? new Thickness(0, 0, 0, 8)
            : new Thickness(0, 42, 8, 34);

        BookPages.Orientation = narrow
            ? BoxContainer.LayoutOrientation.Vertical
            : BoxContainer.LayoutOrientation.Horizontal;
        RuneBookSpine.Visible = !narrow;

        LeftPage.MinWidth = wide ? 520 : narrow ? 0 : 360;
        RightPage.MinWidth = wide ? 620 : narrow ? 0 : 460;
        ToolsPanel.MinWidth = wide ? 126 : 104;
        DrawingControl.MinSize = wide
            ? new Vector2(520, 520)
            : narrow
                ? new Vector2(520, 360)
                : new Vector2(360, 400);

        BottomControls.Orientation = narrow
            ? BoxContainer.LayoutOrientation.Vertical
            : BoxContainer.LayoutOrientation.Horizontal;
        BottomControls.Margin = wide
            ? new Thickness(104, 0, 12, 0)
            : new Thickness(0, 0, 0, 0);
        BottomSpacer.Visible = !narrow;

        PreviousBottomButton.MinSize = wide ? new Vector2(220, 42) : new Vector2(180, 40);
        NextBottomButton.MinSize = wide ? new Vector2(220, 42) : new Vector2(180, 40);
        RipButton.MinSize = wide ? new Vector2(260, 46) : new Vector2(180, 42);
    }

    private bool IsPageRipped(int page)
    {
        return _state?.RippedPages.Contains(page) == true;
    }
}
