using System.Linq;
using System.Numerics;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.UserInterface;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostRolesWindow : DefaultWindow
    {
        public event Action<GhostRoleInfo>? OnRoleRequestButtonClicked;
        public event Action<GhostRoleInfo>? OnRoleFollow;

        private Dictionary<(string name, string description), Collapsible> _collapsibleBoxes = new();
        private HashSet<(string name, string description)> _uncollapsedStates = new();

        // DS14-start
        private Dictionary<string, int> _categoryRoleCounts = new();
        private HashSet<string> _addedCategories = new();
        private string? _currentCategoryFilter;
        private string _searchText = string.Empty;
        // DS14-end


        public GhostRolesWindow()
        {
            RobustXamlLoader.Load(this);

            SearchBar.OnTextChanged += OnSearchTextChanged; // DS14
        }

        public void ClearEntries()
        {
            NoRolesMessage.Visible = true;
            EntryContainer.RemoveAllChildren();
            _collapsibleBoxes.Clear();
            // DS14-start
            TopButtonRow.RemoveAllChildren();
            _addedCategories.Clear();
            _categoryRoleCounts.Clear();
            // DS14-end
        }


        public void SaveCollapsibleBoxesStates()
        {
            _uncollapsedStates.Clear();
            foreach (var (key, collapsible) in _collapsibleBoxes)
            {
                if (collapsible.BodyVisible)
                {
                    _uncollapsedStates.Add(key);
                }
            }
        }

        public void RestoreCollapsibleBoxesStates()
        {
            foreach (var (key, collapsible) in _collapsibleBoxes)
            {
                collapsible.BodyVisible = _uncollapsedStates.Contains(key);
            }
        }

        public void AddEntry(string name, string description, string category, bool hasAccess, FormattedMessage? reason, IEnumerable<GhostRoleInfo> roles, SpriteSystem spriteSystem) // DS14 categories
        {
            NoRolesMessage.Visible = false;
            SearchBar.Visible = true; // DS14

            var ghostRoleInfos = roles.ToList();
            var rolesCount = ghostRoleInfos.Count;

            var info = new GhostRoleInfoBox(name, description);
            var buttons = new GhostRoleButtonsBox(hasAccess, reason, ghostRoleInfos, spriteSystem);
            buttons.OnRoleSelected += OnRoleRequestButtonClicked;
            buttons.OnRoleFollow += OnRoleFollow;
            // DS14-start
            info.AddStyleClass(category);
            info.StyleIdentifier = name;
            buttons.AddStyleClass(category);
            buttons.StyleIdentifier = name;
            // DS14-end

            EntryContainer.AddChild(info);

            // DS14-start
            if (_categoryRoleCounts.ContainsKey(category))
                _categoryRoleCounts[category] += rolesCount;
            else
                _categoryRoleCounts[category] = rolesCount;

            if (!_addedCategories.Contains(category))
            {
                var categoryButton = new Button
                {
                    MinSize = new Vector2(110, 30),
                    Name = category,
                    Text = $"{category} ({_categoryRoleCounts[category]})",
                    Pressed = category == _currentCategoryFilter
                };
                categoryButton.OnPressed += _ => FilterByCategory(category);

                TopButtonRow.AddChild(categoryButton);
                _addedCategories.Add(category);
            }
            else
            {
                var existingButton = TopButtonRow.Children
                    .OfType<Button>()
                    .First(b => b.Name == category);

                existingButton.Text = $"{category} ({_categoryRoleCounts[category]})";
            }
            // DS14-end

            if (rolesCount > 1)
            {
                var buttonHeading = new CollapsibleHeading(Loc.GetString("ghost-roles-window-available-button", ("rolesCount", rolesCount)));

                buttonHeading.AddStyleClass(ContainerButton.StyleClassButton);
                buttonHeading.Label.HorizontalAlignment = HAlignment.Center;
                buttonHeading.Label.HorizontalExpand = true;
                buttonHeading.Margin = new Thickness(8, 0, 8, 2);

                var body = new CollapsibleBody
                {
                    Margin = new Thickness(0, 5, 0, 0),
                };

                // TODO: Add Requirements to this key when it'll be fixed and work as an equality key in GhostRolesEui
                var key = (name, description);

                var collapsible = new Collapsible(buttonHeading, body)
                {
                    Orientation = BoxContainer.LayoutOrientation.Vertical,
                    Margin = new Thickness(0, 0, 0, 8),
                };
                collapsible.AddStyleClass(category); // DS14
                collapsible.StyleIdentifier = name; // DS14
                body.AddChild(buttons);

                EntryContainer.AddChild(collapsible);
                _collapsibleBoxes.Add(key, collapsible);
            }
            else
            {
                EntryContainer.AddChild(buttons);
            }
            UpdateVisibleElements(); // DS14
        }
        // DS14-start
        private void FilterByCategory(string category)
        {
            if (_currentCategoryFilter == category)
            {
                _currentCategoryFilter = null;
                foreach (var button in TopButtonRow.Children.OfType<Button>())
                {
                    button.Pressed = false;
                }
                UpdateVisibleElements();
                return;
            }

            _currentCategoryFilter = category;

            foreach (var btnObj in TopButtonRow.Children.OfType<Button>())
            {
                if (btnObj.Name == category)
                    btnObj.Pressed = true;
                else
                {
                    btnObj.Pressed = false;
                }
            }
            UpdateVisibleElements();
        }
        private bool ElementIsVisible(Control elem)
        {
            return
                (string.IsNullOrEmpty(_searchText)
                 || elem.StyleIdentifier == null
                 || elem.StyleIdentifier.Contains(_searchText, StringComparison.OrdinalIgnoreCase))
                && (_currentCategoryFilter is null
                    || elem.StyleClasses.Contains(_currentCategoryFilter));
        }

        private void UpdateVisibleElements()
        {
            foreach (var child in EntryContainer.Children)
            {
                child.Visible = ElementIsVisible(child);
            }
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            _searchText = args.Text;

            UpdateVisibleElements();
            // Reset scroll bar so they can see the relevant results.
            RoleScroll.SetScrollValue(Vector2.Zero);
        }
        // DS14-end
    }
}
